/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as withHeaderFooterRouteRouteImport } from './routes/(with-header-footer)/route'
import { Route as withHeaderFooterIndexRouteImport } from './routes/(with-header-footer)/index'
import { Route as withHeaderFooterCompanyIndexRouteImport } from './routes/(with-header-footer)/company/index'
import { Route as withHeaderFooterPartnershipIndexRouteImport } from './routes/(with-header-footer)/partnership/index'
import { Route as withHeaderFooterToolsIndexRouteImport } from './routes/(with-header-footer)/tools/index'
import { Route as withHeaderFooterTradingIndexRouteImport } from './routes/(with-header-footer)/trading/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/route'
import { Route as withoutHeaderFooterauthenticatednewUserRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/(new-user)/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as withHeaderFooterCompanyAboutIndexRouteImport } from './routes/(with-header-footer)/company/about/index'
import { Route as withHeaderFooterCompanyAwardsIndexRouteImport } from './routes/(with-header-footer)/company/awards/index'
import { Route as withHeaderFooterCompanyNewsIndexRouteImport } from './routes/(with-header-footer)/company/news/index'
import { Route as withHeaderFooterPartnershipAffiliateIndexRouteImport } from './routes/(with-header-footer)/partnership/affiliate/index'
import { Route as withHeaderFooterPartnershipIbIndexRouteImport } from './routes/(with-header-footer)/partnership/ib/index'
import { Route as withHeaderFooterTradingAccountsIndexRouteImport } from './routes/(with-header-footer)/trading/accounts/index'
import { Route as withHeaderFooterTradingInstrumentsIndexRouteImport } from './routes/(with-header-footer)/trading/instruments/index'
import { Route as withHeaderFooterTradingPlatformsIndexRouteImport } from './routes/(with-header-footer)/trading/platforms/index'
import { Route as withHeaderFooterTradingSyntxIndexRouteImport } from './routes/(with-header-footer)/trading/syntx/index'
import { Route as withoutHeaderFooterauthenticatedRedirectSigninIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/redirect-signin/index'
import { Route as withoutHeaderFooterguestSigninIndexRouteImport } from './routes/(without-header-footer)/(guest)/signin/index'
import { Route as withoutHeaderFooterleagalPagesCookiePolicyIndexRouteImport } from './routes/(without-header-footer)/(leagal-pages)/cookie-policy/index'
import { Route as withoutHeaderFooterleagalPagesPrivacyPolicyIndexRouteImport } from './routes/(without-header-footer)/(leagal-pages)/privacy-policy/index'
import { Route as withoutHeaderFooterleagalPagesTermsOfServiceIndexRouteImport } from './routes/(without-header-footer)/(leagal-pages)/terms-of-service/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserDashboardIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/dashboard/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserDepositIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/deposit/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserMiningIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/mining/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserReferralIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/referral/index'
import { Route as withoutHeaderFooterauthenticatednewUserWelcomeIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(new-user)/welcome/index'

const withHeaderFooterRouteRoute = withHeaderFooterRouteRouteImport.update({
  id: '/(with-header-footer)',
  getParentRoute: () => rootRouteImport,
} as any)
const withHeaderFooterIndexRoute = withHeaderFooterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => withHeaderFooterRouteRoute,
} as any)
const withHeaderFooterCompanyIndexRoute =
  withHeaderFooterCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipIndexRoute =
  withHeaderFooterPartnershipIndexRouteImport.update({
    id: '/partnership/',
    path: '/partnership/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterToolsIndexRoute =
  withHeaderFooterToolsIndexRouteImport.update({
    id: '/tools/',
    path: '/tools/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingIndexRoute =
  withHeaderFooterTradingIndexRouteImport.update({
    id: '/trading/',
    path: '/trading/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserRouteRoute =
  withoutHeaderFooterauthenticatedexistingUserRouteRouteImport.update({
    id: '/(without-header-footer)/(authenticated)/(existing-user)',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterauthenticatednewUserRouteRoute =
  withoutHeaderFooterauthenticatednewUserRouteRouteImport.update({
    id: '/(without-header-footer)/(authenticated)/(new-user)',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const withHeaderFooterCompanyAboutIndexRoute =
  withHeaderFooterCompanyAboutIndexRouteImport.update({
    id: '/company/about/',
    path: '/company/about/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyAwardsIndexRoute =
  withHeaderFooterCompanyAwardsIndexRouteImport.update({
    id: '/company/awards/',
    path: '/company/awards/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyNewsIndexRoute =
  withHeaderFooterCompanyNewsIndexRouteImport.update({
    id: '/company/news/',
    path: '/company/news/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipAffiliateIndexRoute =
  withHeaderFooterPartnershipAffiliateIndexRouteImport.update({
    id: '/partnership/affiliate/',
    path: '/partnership/affiliate/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipIbIndexRoute =
  withHeaderFooterPartnershipIbIndexRouteImport.update({
    id: '/partnership/ib/',
    path: '/partnership/ib/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingAccountsIndexRoute =
  withHeaderFooterTradingAccountsIndexRouteImport.update({
    id: '/trading/accounts/',
    path: '/trading/accounts/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingInstrumentsIndexRoute =
  withHeaderFooterTradingInstrumentsIndexRouteImport.update({
    id: '/trading/instruments/',
    path: '/trading/instruments/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingPlatformsIndexRoute =
  withHeaderFooterTradingPlatformsIndexRouteImport.update({
    id: '/trading/platforms/',
    path: '/trading/platforms/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingSyntxIndexRoute =
  withHeaderFooterTradingSyntxIndexRouteImport.update({
    id: '/trading/syntx/',
    path: '/trading/syntx/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedRedirectSigninIndexRoute =
  withoutHeaderFooterauthenticatedRedirectSigninIndexRouteImport.update({
    id: '/(without-header-footer)/(authenticated)/redirect-signin/',
    path: '/redirect-signin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterguestSigninIndexRoute =
  withoutHeaderFooterguestSigninIndexRouteImport.update({
    id: '/(without-header-footer)/(guest)/signin/',
    path: '/signin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterleagalPagesCookiePolicyIndexRoute =
  withoutHeaderFooterleagalPagesCookiePolicyIndexRouteImport.update({
    id: '/(without-header-footer)/(leagal-pages)/cookie-policy/',
    path: '/cookie-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute =
  withoutHeaderFooterleagalPagesPrivacyPolicyIndexRouteImport.update({
    id: '/(without-header-footer)/(leagal-pages)/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute =
  withoutHeaderFooterleagalPagesTermsOfServiceIndexRouteImport.update({
    id: '/(without-header-footer)/(leagal-pages)/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserDepositIndexRouteImport.update({
    id: '/deposit/',
    path: '/deposit/',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserMiningIndexRouteImport.update({
    id: '/mining/',
    path: '/mining/',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserReferralIndexRouteImport.update({
    id: '/referral/',
    path: '/referral/',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute =
  withoutHeaderFooterauthenticatednewUserWelcomeIndexRouteImport.update({
    id: '/welcome/',
    path: '/welcome/',
    getParentRoute: () => withoutHeaderFooterauthenticatednewUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof withHeaderFooterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/company/': typeof withHeaderFooterCompanyIndexRoute
  '/partnership/': typeof withHeaderFooterPartnershipIndexRoute
  '/tools/': typeof withHeaderFooterToolsIndexRoute
  '/trading/': typeof withHeaderFooterTradingIndexRoute
  '/company/about/': typeof withHeaderFooterCompanyAboutIndexRoute
  '/company/awards/': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/company/news/': typeof withHeaderFooterCompanyNewsIndexRoute
  '/partnership/affiliate/': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/partnership/ib/': typeof withHeaderFooterPartnershipIbIndexRoute
  '/trading/accounts/': typeof withHeaderFooterTradingAccountsIndexRoute
  '/trading/instruments/': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/trading/platforms/': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/trading/syntx/': typeof withHeaderFooterTradingSyntxIndexRoute
  '/redirect-signin/': typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  '/signin/': typeof withoutHeaderFooterguestSigninIndexRoute
  '/cookie-policy/': typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  '/privacy-policy/': typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
  '/dashboard/': typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  '/deposit/': typeof withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute
  '/mining/': typeof withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute
  '/referral/': typeof withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute
  '/welcome/': typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof withHeaderFooterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/company': typeof withHeaderFooterCompanyIndexRoute
  '/partnership': typeof withHeaderFooterPartnershipIndexRoute
  '/tools': typeof withHeaderFooterToolsIndexRoute
  '/trading': typeof withHeaderFooterTradingIndexRoute
  '/company/about': typeof withHeaderFooterCompanyAboutIndexRoute
  '/company/awards': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/company/news': typeof withHeaderFooterCompanyNewsIndexRoute
  '/partnership/affiliate': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/partnership/ib': typeof withHeaderFooterPartnershipIbIndexRoute
  '/trading/accounts': typeof withHeaderFooterTradingAccountsIndexRoute
  '/trading/instruments': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/trading/platforms': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/trading/syntx': typeof withHeaderFooterTradingSyntxIndexRoute
  '/redirect-signin': typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  '/signin': typeof withoutHeaderFooterguestSigninIndexRoute
  '/cookie-policy': typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  '/privacy-policy': typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  '/terms-of-service': typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
  '/dashboard': typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  '/deposit': typeof withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute
  '/mining': typeof withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute
  '/referral': typeof withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute
  '/welcome': typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(with-header-footer)': typeof withHeaderFooterRouteRouteWithChildren
  '/(with-header-footer)/': typeof withHeaderFooterIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)': typeof withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren
  '/(without-header-footer)/(authenticated)/(new-user)': typeof withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(with-header-footer)/company/': typeof withHeaderFooterCompanyIndexRoute
  '/(with-header-footer)/partnership/': typeof withHeaderFooterPartnershipIndexRoute
  '/(with-header-footer)/tools/': typeof withHeaderFooterToolsIndexRoute
  '/(with-header-footer)/trading/': typeof withHeaderFooterTradingIndexRoute
  '/(with-header-footer)/company/about/': typeof withHeaderFooterCompanyAboutIndexRoute
  '/(with-header-footer)/company/awards/': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/(with-header-footer)/company/news/': typeof withHeaderFooterCompanyNewsIndexRoute
  '/(with-header-footer)/partnership/affiliate/': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/(with-header-footer)/partnership/ib/': typeof withHeaderFooterPartnershipIbIndexRoute
  '/(with-header-footer)/trading/accounts/': typeof withHeaderFooterTradingAccountsIndexRoute
  '/(with-header-footer)/trading/instruments/': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/(with-header-footer)/trading/platforms/': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/(with-header-footer)/trading/syntx/': typeof withHeaderFooterTradingSyntxIndexRoute
  '/(without-header-footer)/(authenticated)/redirect-signin/': typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  '/(without-header-footer)/(guest)/signin/': typeof withoutHeaderFooterguestSigninIndexRoute
  '/(without-header-footer)/(leagal-pages)/cookie-policy/': typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  '/(without-header-footer)/(leagal-pages)/privacy-policy/': typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  '/(without-header-footer)/(leagal-pages)/terms-of-service/': typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/': typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/deposit/': typeof withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/mining/': typeof withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/referral/': typeof withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute
  '/(without-header-footer)/(authenticated)/(new-user)/welcome/': typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/company/'
    | '/partnership/'
    | '/tools/'
    | '/trading/'
    | '/company/about/'
    | '/company/awards/'
    | '/company/news/'
    | '/partnership/affiliate/'
    | '/partnership/ib/'
    | '/trading/accounts/'
    | '/trading/instruments/'
    | '/trading/platforms/'
    | '/trading/syntx/'
    | '/redirect-signin/'
    | '/signin/'
    | '/cookie-policy/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/dashboard/'
    | '/deposit/'
    | '/mining/'
    | '/referral/'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/company'
    | '/partnership'
    | '/tools'
    | '/trading'
    | '/company/about'
    | '/company/awards'
    | '/company/news'
    | '/partnership/affiliate'
    | '/partnership/ib'
    | '/trading/accounts'
    | '/trading/instruments'
    | '/trading/platforms'
    | '/trading/syntx'
    | '/redirect-signin'
    | '/signin'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard'
    | '/deposit'
    | '/mining'
    | '/referral'
    | '/welcome'
  id:
    | '__root__'
    | '/(with-header-footer)'
    | '/(with-header-footer)/'
    | '/(without-header-footer)/(authenticated)/(existing-user)'
    | '/(without-header-footer)/(authenticated)/(new-user)'
    | '/api/auth/$'
    | '/(with-header-footer)/company/'
    | '/(with-header-footer)/partnership/'
    | '/(with-header-footer)/tools/'
    | '/(with-header-footer)/trading/'
    | '/(with-header-footer)/company/about/'
    | '/(with-header-footer)/company/awards/'
    | '/(with-header-footer)/company/news/'
    | '/(with-header-footer)/partnership/affiliate/'
    | '/(with-header-footer)/partnership/ib/'
    | '/(with-header-footer)/trading/accounts/'
    | '/(with-header-footer)/trading/instruments/'
    | '/(with-header-footer)/trading/platforms/'
    | '/(with-header-footer)/trading/syntx/'
    | '/(without-header-footer)/(authenticated)/redirect-signin/'
    | '/(without-header-footer)/(guest)/signin/'
    | '/(without-header-footer)/(leagal-pages)/cookie-policy/'
    | '/(without-header-footer)/(leagal-pages)/privacy-policy/'
    | '/(without-header-footer)/(leagal-pages)/terms-of-service/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/deposit/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/mining/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/referral/'
    | '/(without-header-footer)/(authenticated)/(new-user)/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  withHeaderFooterRouteRoute: typeof withHeaderFooterRouteRouteWithChildren
  withoutHeaderFooterauthenticatedexistingUserRouteRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren
  withoutHeaderFooterauthenticatednewUserRouteRoute: typeof withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  withoutHeaderFooterauthenticatedRedirectSigninIndexRoute: typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  withoutHeaderFooterguestSigninIndexRoute: typeof withoutHeaderFooterguestSigninIndexRoute
  withoutHeaderFooterleagalPagesCookiePolicyIndexRoute: typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute: typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute: typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(with-header-footer)': {
      id: '/(with-header-footer)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withHeaderFooterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/': {
      id: '/(with-header-footer)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof withHeaderFooterIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/': {
      id: '/(with-header-footer)/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof withHeaderFooterCompanyIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/': {
      id: '/(with-header-footer)/partnership/'
      path: '/partnership'
      fullPath: '/partnership/'
      preLoaderRoute: typeof withHeaderFooterPartnershipIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/tools/': {
      id: '/(with-header-footer)/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof withHeaderFooterToolsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/': {
      id: '/(with-header-footer)/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof withHeaderFooterTradingIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(authenticated)/(new-user)': {
      id: '/(without-header-footer)/(authenticated)/(new-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatednewUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/company/about/': {
      id: '/(with-header-footer)/company/about/'
      path: '/company/about'
      fullPath: '/company/about/'
      preLoaderRoute: typeof withHeaderFooterCompanyAboutIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/awards/': {
      id: '/(with-header-footer)/company/awards/'
      path: '/company/awards'
      fullPath: '/company/awards/'
      preLoaderRoute: typeof withHeaderFooterCompanyAwardsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/news/': {
      id: '/(with-header-footer)/company/news/'
      path: '/company/news'
      fullPath: '/company/news/'
      preLoaderRoute: typeof withHeaderFooterCompanyNewsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/affiliate/': {
      id: '/(with-header-footer)/partnership/affiliate/'
      path: '/partnership/affiliate'
      fullPath: '/partnership/affiliate/'
      preLoaderRoute: typeof withHeaderFooterPartnershipAffiliateIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/ib/': {
      id: '/(with-header-footer)/partnership/ib/'
      path: '/partnership/ib'
      fullPath: '/partnership/ib/'
      preLoaderRoute: typeof withHeaderFooterPartnershipIbIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/accounts/': {
      id: '/(with-header-footer)/trading/accounts/'
      path: '/trading/accounts'
      fullPath: '/trading/accounts/'
      preLoaderRoute: typeof withHeaderFooterTradingAccountsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/instruments/': {
      id: '/(with-header-footer)/trading/instruments/'
      path: '/trading/instruments'
      fullPath: '/trading/instruments/'
      preLoaderRoute: typeof withHeaderFooterTradingInstrumentsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/platforms/': {
      id: '/(with-header-footer)/trading/platforms/'
      path: '/trading/platforms'
      fullPath: '/trading/platforms/'
      preLoaderRoute: typeof withHeaderFooterTradingPlatformsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/syntx/': {
      id: '/(with-header-footer)/trading/syntx/'
      path: '/trading/syntx'
      fullPath: '/trading/syntx/'
      preLoaderRoute: typeof withHeaderFooterTradingSyntxIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(without-header-footer)/(authenticated)/redirect-signin/': {
      id: '/(without-header-footer)/(authenticated)/redirect-signin/'
      path: '/redirect-signin'
      fullPath: '/redirect-signin/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(guest)/signin/': {
      id: '/(without-header-footer)/(guest)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof withoutHeaderFooterguestSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(leagal-pages)/cookie-policy/': {
      id: '/(without-header-footer)/(leagal-pages)/cookie-policy/'
      path: '/cookie-policy'
      fullPath: '/cookie-policy/'
      preLoaderRoute: typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(leagal-pages)/privacy-policy/': {
      id: '/(without-header-footer)/(leagal-pages)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(leagal-pages)/terms-of-service/': {
      id: '/(without-header-footer)/(leagal-pages)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/deposit/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/deposit/'
      path: '/deposit'
      fullPath: '/deposit/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserDepositIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/mining/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/mining/'
      path: '/mining'
      fullPath: '/mining/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserMiningIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/referral/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/referral/'
      path: '/referral'
      fullPath: '/referral/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserReferralIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(new-user)/welcome/': {
      id: '/(without-header-footer)/(authenticated)/(new-user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatednewUserRouteRoute
    }
  }
}

interface withHeaderFooterRouteRouteChildren {
  withHeaderFooterIndexRoute: typeof withHeaderFooterIndexRoute
  withHeaderFooterCompanyIndexRoute: typeof withHeaderFooterCompanyIndexRoute
  withHeaderFooterPartnershipIndexRoute: typeof withHeaderFooterPartnershipIndexRoute
  withHeaderFooterToolsIndexRoute: typeof withHeaderFooterToolsIndexRoute
  withHeaderFooterTradingIndexRoute: typeof withHeaderFooterTradingIndexRoute
  withHeaderFooterCompanyAboutIndexRoute: typeof withHeaderFooterCompanyAboutIndexRoute
  withHeaderFooterCompanyAwardsIndexRoute: typeof withHeaderFooterCompanyAwardsIndexRoute
  withHeaderFooterCompanyNewsIndexRoute: typeof withHeaderFooterCompanyNewsIndexRoute
  withHeaderFooterPartnershipAffiliateIndexRoute: typeof withHeaderFooterPartnershipAffiliateIndexRoute
  withHeaderFooterPartnershipIbIndexRoute: typeof withHeaderFooterPartnershipIbIndexRoute
  withHeaderFooterTradingAccountsIndexRoute: typeof withHeaderFooterTradingAccountsIndexRoute
  withHeaderFooterTradingInstrumentsIndexRoute: typeof withHeaderFooterTradingInstrumentsIndexRoute
  withHeaderFooterTradingPlatformsIndexRoute: typeof withHeaderFooterTradingPlatformsIndexRoute
  withHeaderFooterTradingSyntxIndexRoute: typeof withHeaderFooterTradingSyntxIndexRoute
}

const withHeaderFooterRouteRouteChildren: withHeaderFooterRouteRouteChildren = {
  withHeaderFooterIndexRoute: withHeaderFooterIndexRoute,
  withHeaderFooterCompanyIndexRoute: withHeaderFooterCompanyIndexRoute,
  withHeaderFooterPartnershipIndexRoute: withHeaderFooterPartnershipIndexRoute,
  withHeaderFooterToolsIndexRoute: withHeaderFooterToolsIndexRoute,
  withHeaderFooterTradingIndexRoute: withHeaderFooterTradingIndexRoute,
  withHeaderFooterCompanyAboutIndexRoute:
    withHeaderFooterCompanyAboutIndexRoute,
  withHeaderFooterCompanyAwardsIndexRoute:
    withHeaderFooterCompanyAwardsIndexRoute,
  withHeaderFooterCompanyNewsIndexRoute: withHeaderFooterCompanyNewsIndexRoute,
  withHeaderFooterPartnershipAffiliateIndexRoute:
    withHeaderFooterPartnershipAffiliateIndexRoute,
  withHeaderFooterPartnershipIbIndexRoute:
    withHeaderFooterPartnershipIbIndexRoute,
  withHeaderFooterTradingAccountsIndexRoute:
    withHeaderFooterTradingAccountsIndexRoute,
  withHeaderFooterTradingInstrumentsIndexRoute:
    withHeaderFooterTradingInstrumentsIndexRoute,
  withHeaderFooterTradingPlatformsIndexRoute:
    withHeaderFooterTradingPlatformsIndexRoute,
  withHeaderFooterTradingSyntxIndexRoute:
    withHeaderFooterTradingSyntxIndexRoute,
}

const withHeaderFooterRouteRouteWithChildren =
  withHeaderFooterRouteRoute._addFileChildren(
    withHeaderFooterRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren {
  withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute
  withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute
  withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute
}

const withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren: withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute,
    withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserDepositIndexRoute,
    withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserMiningIndexRoute,
    withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserReferralIndexRoute,
  }

const withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren =
  withoutHeaderFooterauthenticatedexistingUserRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatednewUserRouteRouteChildren {
  withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute: typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
}

const withoutHeaderFooterauthenticatednewUserRouteRouteChildren: withoutHeaderFooterauthenticatednewUserRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute:
      withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute,
  }

const withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren =
  withoutHeaderFooterauthenticatednewUserRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatednewUserRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  withHeaderFooterRouteRoute: withHeaderFooterRouteRouteWithChildren,
  withoutHeaderFooterauthenticatedexistingUserRouteRoute:
    withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren,
  withoutHeaderFooterauthenticatednewUserRouteRoute:
    withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  withoutHeaderFooterauthenticatedRedirectSigninIndexRoute:
    withoutHeaderFooterauthenticatedRedirectSigninIndexRoute,
  withoutHeaderFooterguestSigninIndexRoute:
    withoutHeaderFooterguestSigninIndexRoute,
  withoutHeaderFooterleagalPagesCookiePolicyIndexRoute:
    withoutHeaderFooterleagalPagesCookiePolicyIndexRoute,
  withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute:
    withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute,
  withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute:
    withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
