/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as withHeaderFooterRouteRouteImport } from './routes/(with-header-footer)/route'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as withHeaderFooterIndexRouteImport } from './routes/(with-header-footer)/index'
import { Route as withoutHeaderFooterTermsOfServiceIndexRouteImport } from './routes/(without-header-footer)/terms-of-service/index'
import { Route as withoutHeaderFooterPrivacyPolicyIndexRouteImport } from './routes/(without-header-footer)/privacy-policy/index'
import { Route as withoutHeaderFooterCookiePolicyIndexRouteImport } from './routes/(without-header-footer)/cookie-policy/index'
import { Route as withHeaderFooterTradingIndexRouteImport } from './routes/(with-header-footer)/trading/index'
import { Route as withHeaderFooterToolsIndexRouteImport } from './routes/(with-header-footer)/tools/index'
import { Route as withHeaderFooterPromotionsIndexRouteImport } from './routes/(with-header-footer)/promotions/index'
import { Route as withHeaderFooterPartnershipIndexRouteImport } from './routes/(with-header-footer)/partnership/index'
import { Route as withHeaderFooterEducationIndexRouteImport } from './routes/(with-header-footer)/education/index'
import { Route as withHeaderFooterCompanyIndexRouteImport } from './routes/(with-header-footer)/company/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as withHeaderFooterTradingSyntxIndexRouteImport } from './routes/(with-header-footer)/trading/syntx/index'
import { Route as withHeaderFooterTradingPlatformsIndexRouteImport } from './routes/(with-header-footer)/trading/platforms/index'
import { Route as withHeaderFooterTradingInstrumentsIndexRouteImport } from './routes/(with-header-footer)/trading/instruments/index'
import { Route as withHeaderFooterTradingAccountsIndexRouteImport } from './routes/(with-header-footer)/trading/accounts/index'
import { Route as withHeaderFooterPartnershipIbIndexRouteImport } from './routes/(with-header-footer)/partnership/ib/index'
import { Route as withHeaderFooterPartnershipAffiliateIndexRouteImport } from './routes/(with-header-footer)/partnership/affiliate/index'
import { Route as withHeaderFooterEducationWebinarsIndexRouteImport } from './routes/(with-header-footer)/education/webinars/index'
import { Route as withHeaderFooterEducationGuidesIndexRouteImport } from './routes/(with-header-footer)/education/guides/index'
import { Route as withHeaderFooterCompanyNewsIndexRouteImport } from './routes/(with-header-footer)/company/news/index'
import { Route as withHeaderFooterCompanyAwardsIndexRouteImport } from './routes/(with-header-footer)/company/awards/index'
import { Route as withHeaderFooterCompanyAboutIndexRouteImport } from './routes/(with-header-footer)/company/about/index'

const withHeaderFooterRouteRoute = withHeaderFooterRouteRouteImport.update({
  id: '/(with-header-footer)',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const withHeaderFooterIndexRoute = withHeaderFooterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => withHeaderFooterRouteRoute,
} as any)
const withoutHeaderFooterTermsOfServiceIndexRoute =
  withoutHeaderFooterTermsOfServiceIndexRouteImport.update({
    id: '/(without-header-footer)/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterPrivacyPolicyIndexRoute =
  withoutHeaderFooterPrivacyPolicyIndexRouteImport.update({
    id: '/(without-header-footer)/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterCookiePolicyIndexRoute =
  withoutHeaderFooterCookiePolicyIndexRouteImport.update({
    id: '/(without-header-footer)/cookie-policy/',
    path: '/cookie-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withHeaderFooterTradingIndexRoute =
  withHeaderFooterTradingIndexRouteImport.update({
    id: '/trading/',
    path: '/trading/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterToolsIndexRoute =
  withHeaderFooterToolsIndexRouteImport.update({
    id: '/tools/',
    path: '/tools/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPromotionsIndexRoute =
  withHeaderFooterPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipIndexRoute =
  withHeaderFooterPartnershipIndexRouteImport.update({
    id: '/partnership/',
    path: '/partnership/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterEducationIndexRoute =
  withHeaderFooterEducationIndexRouteImport.update({
    id: '/education/',
    path: '/education/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyIndexRoute =
  withHeaderFooterCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const withHeaderFooterTradingSyntxIndexRoute =
  withHeaderFooterTradingSyntxIndexRouteImport.update({
    id: '/trading/syntx/',
    path: '/trading/syntx/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingPlatformsIndexRoute =
  withHeaderFooterTradingPlatformsIndexRouteImport.update({
    id: '/trading/platforms/',
    path: '/trading/platforms/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingInstrumentsIndexRoute =
  withHeaderFooterTradingInstrumentsIndexRouteImport.update({
    id: '/trading/instruments/',
    path: '/trading/instruments/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingAccountsIndexRoute =
  withHeaderFooterTradingAccountsIndexRouteImport.update({
    id: '/trading/accounts/',
    path: '/trading/accounts/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipIbIndexRoute =
  withHeaderFooterPartnershipIbIndexRouteImport.update({
    id: '/partnership/ib/',
    path: '/partnership/ib/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipAffiliateIndexRoute =
  withHeaderFooterPartnershipAffiliateIndexRouteImport.update({
    id: '/partnership/affiliate/',
    path: '/partnership/affiliate/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterEducationWebinarsIndexRoute =
  withHeaderFooterEducationWebinarsIndexRouteImport.update({
    id: '/education/webinars/',
    path: '/education/webinars/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterEducationGuidesIndexRoute =
  withHeaderFooterEducationGuidesIndexRouteImport.update({
    id: '/education/guides/',
    path: '/education/guides/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyNewsIndexRoute =
  withHeaderFooterCompanyNewsIndexRouteImport.update({
    id: '/company/news/',
    path: '/company/news/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyAwardsIndexRoute =
  withHeaderFooterCompanyAwardsIndexRouteImport.update({
    id: '/company/awards/',
    path: '/company/awards/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyAboutIndexRoute =
  withHeaderFooterCompanyAboutIndexRouteImport.update({
    id: '/company/about/',
    path: '/company/about/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof withHeaderFooterIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/company/': typeof withHeaderFooterCompanyIndexRoute
  '/education/': typeof withHeaderFooterEducationIndexRoute
  '/partnership/': typeof withHeaderFooterPartnershipIndexRoute
  '/promotions/': typeof withHeaderFooterPromotionsIndexRoute
  '/tools/': typeof withHeaderFooterToolsIndexRoute
  '/trading/': typeof withHeaderFooterTradingIndexRoute
  '/cookie-policy/': typeof withoutHeaderFooterCookiePolicyIndexRoute
  '/privacy-policy/': typeof withoutHeaderFooterPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof withoutHeaderFooterTermsOfServiceIndexRoute
  '/company/about/': typeof withHeaderFooterCompanyAboutIndexRoute
  '/company/awards/': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/company/news/': typeof withHeaderFooterCompanyNewsIndexRoute
  '/education/guides/': typeof withHeaderFooterEducationGuidesIndexRoute
  '/education/webinars/': typeof withHeaderFooterEducationWebinarsIndexRoute
  '/partnership/affiliate/': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/partnership/ib/': typeof withHeaderFooterPartnershipIbIndexRoute
  '/trading/accounts/': typeof withHeaderFooterTradingAccountsIndexRoute
  '/trading/instruments/': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/trading/platforms/': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/trading/syntx/': typeof withHeaderFooterTradingSyntxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof withHeaderFooterIndexRoute
  '/signin': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/company': typeof withHeaderFooterCompanyIndexRoute
  '/education': typeof withHeaderFooterEducationIndexRoute
  '/partnership': typeof withHeaderFooterPartnershipIndexRoute
  '/promotions': typeof withHeaderFooterPromotionsIndexRoute
  '/tools': typeof withHeaderFooterToolsIndexRoute
  '/trading': typeof withHeaderFooterTradingIndexRoute
  '/cookie-policy': typeof withoutHeaderFooterCookiePolicyIndexRoute
  '/privacy-policy': typeof withoutHeaderFooterPrivacyPolicyIndexRoute
  '/terms-of-service': typeof withoutHeaderFooterTermsOfServiceIndexRoute
  '/company/about': typeof withHeaderFooterCompanyAboutIndexRoute
  '/company/awards': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/company/news': typeof withHeaderFooterCompanyNewsIndexRoute
  '/education/guides': typeof withHeaderFooterEducationGuidesIndexRoute
  '/education/webinars': typeof withHeaderFooterEducationWebinarsIndexRoute
  '/partnership/affiliate': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/partnership/ib': typeof withHeaderFooterPartnershipIbIndexRoute
  '/trading/accounts': typeof withHeaderFooterTradingAccountsIndexRoute
  '/trading/instruments': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/trading/platforms': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/trading/syntx': typeof withHeaderFooterTradingSyntxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(with-header-footer)': typeof withHeaderFooterRouteRouteWithChildren
  '/(with-header-footer)/': typeof withHeaderFooterIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(with-header-footer)/company/': typeof withHeaderFooterCompanyIndexRoute
  '/(with-header-footer)/education/': typeof withHeaderFooterEducationIndexRoute
  '/(with-header-footer)/partnership/': typeof withHeaderFooterPartnershipIndexRoute
  '/(with-header-footer)/promotions/': typeof withHeaderFooterPromotionsIndexRoute
  '/(with-header-footer)/tools/': typeof withHeaderFooterToolsIndexRoute
  '/(with-header-footer)/trading/': typeof withHeaderFooterTradingIndexRoute
  '/(without-header-footer)/cookie-policy/': typeof withoutHeaderFooterCookiePolicyIndexRoute
  '/(without-header-footer)/privacy-policy/': typeof withoutHeaderFooterPrivacyPolicyIndexRoute
  '/(without-header-footer)/terms-of-service/': typeof withoutHeaderFooterTermsOfServiceIndexRoute
  '/(with-header-footer)/company/about/': typeof withHeaderFooterCompanyAboutIndexRoute
  '/(with-header-footer)/company/awards/': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/(with-header-footer)/company/news/': typeof withHeaderFooterCompanyNewsIndexRoute
  '/(with-header-footer)/education/guides/': typeof withHeaderFooterEducationGuidesIndexRoute
  '/(with-header-footer)/education/webinars/': typeof withHeaderFooterEducationWebinarsIndexRoute
  '/(with-header-footer)/partnership/affiliate/': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/(with-header-footer)/partnership/ib/': typeof withHeaderFooterPartnershipIbIndexRoute
  '/(with-header-footer)/trading/accounts/': typeof withHeaderFooterTradingAccountsIndexRoute
  '/(with-header-footer)/trading/instruments/': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/(with-header-footer)/trading/platforms/': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/(with-header-footer)/trading/syntx/': typeof withHeaderFooterTradingSyntxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin/'
    | '/api/auth/$'
    | '/company/'
    | '/education/'
    | '/partnership/'
    | '/promotions/'
    | '/tools/'
    | '/trading/'
    | '/cookie-policy/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/company/about/'
    | '/company/awards/'
    | '/company/news/'
    | '/education/guides/'
    | '/education/webinars/'
    | '/partnership/affiliate/'
    | '/partnership/ib/'
    | '/trading/accounts/'
    | '/trading/instruments/'
    | '/trading/platforms/'
    | '/trading/syntx/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/api/auth/$'
    | '/company'
    | '/education'
    | '/partnership'
    | '/promotions'
    | '/tools'
    | '/trading'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/company/about'
    | '/company/awards'
    | '/company/news'
    | '/education/guides'
    | '/education/webinars'
    | '/partnership/affiliate'
    | '/partnership/ib'
    | '/trading/accounts'
    | '/trading/instruments'
    | '/trading/platforms'
    | '/trading/syntx'
  id:
    | '__root__'
    | '/(with-header-footer)'
    | '/(with-header-footer)/'
    | '/signin/'
    | '/api/auth/$'
    | '/(with-header-footer)/company/'
    | '/(with-header-footer)/education/'
    | '/(with-header-footer)/partnership/'
    | '/(with-header-footer)/promotions/'
    | '/(with-header-footer)/tools/'
    | '/(with-header-footer)/trading/'
    | '/(without-header-footer)/cookie-policy/'
    | '/(without-header-footer)/privacy-policy/'
    | '/(without-header-footer)/terms-of-service/'
    | '/(with-header-footer)/company/about/'
    | '/(with-header-footer)/company/awards/'
    | '/(with-header-footer)/company/news/'
    | '/(with-header-footer)/education/guides/'
    | '/(with-header-footer)/education/webinars/'
    | '/(with-header-footer)/partnership/affiliate/'
    | '/(with-header-footer)/partnership/ib/'
    | '/(with-header-footer)/trading/accounts/'
    | '/(with-header-footer)/trading/instruments/'
    | '/(with-header-footer)/trading/platforms/'
    | '/(with-header-footer)/trading/syntx/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  withHeaderFooterRouteRoute: typeof withHeaderFooterRouteRouteWithChildren
  SigninIndexRoute: typeof SigninIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  withoutHeaderFooterCookiePolicyIndexRoute: typeof withoutHeaderFooterCookiePolicyIndexRoute
  withoutHeaderFooterPrivacyPolicyIndexRoute: typeof withoutHeaderFooterPrivacyPolicyIndexRoute
  withoutHeaderFooterTermsOfServiceIndexRoute: typeof withoutHeaderFooterTermsOfServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(with-header-footer)': {
      id: '/(with-header-footer)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withHeaderFooterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/': {
      id: '/(with-header-footer)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof withHeaderFooterIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(without-header-footer)/terms-of-service/': {
      id: '/(without-header-footer)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof withoutHeaderFooterTermsOfServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/privacy-policy/': {
      id: '/(without-header-footer)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof withoutHeaderFooterPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/cookie-policy/': {
      id: '/(without-header-footer)/cookie-policy/'
      path: '/cookie-policy'
      fullPath: '/cookie-policy/'
      preLoaderRoute: typeof withoutHeaderFooterCookiePolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/trading/': {
      id: '/(with-header-footer)/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof withHeaderFooterTradingIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/tools/': {
      id: '/(with-header-footer)/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof withHeaderFooterToolsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/promotions/': {
      id: '/(with-header-footer)/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof withHeaderFooterPromotionsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/': {
      id: '/(with-header-footer)/partnership/'
      path: '/partnership'
      fullPath: '/partnership/'
      preLoaderRoute: typeof withHeaderFooterPartnershipIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/education/': {
      id: '/(with-header-footer)/education/'
      path: '/education'
      fullPath: '/education/'
      preLoaderRoute: typeof withHeaderFooterEducationIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/': {
      id: '/(with-header-footer)/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof withHeaderFooterCompanyIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/trading/syntx/': {
      id: '/(with-header-footer)/trading/syntx/'
      path: '/trading/syntx'
      fullPath: '/trading/syntx/'
      preLoaderRoute: typeof withHeaderFooterTradingSyntxIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/platforms/': {
      id: '/(with-header-footer)/trading/platforms/'
      path: '/trading/platforms'
      fullPath: '/trading/platforms/'
      preLoaderRoute: typeof withHeaderFooterTradingPlatformsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/instruments/': {
      id: '/(with-header-footer)/trading/instruments/'
      path: '/trading/instruments'
      fullPath: '/trading/instruments/'
      preLoaderRoute: typeof withHeaderFooterTradingInstrumentsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/accounts/': {
      id: '/(with-header-footer)/trading/accounts/'
      path: '/trading/accounts'
      fullPath: '/trading/accounts/'
      preLoaderRoute: typeof withHeaderFooterTradingAccountsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/ib/': {
      id: '/(with-header-footer)/partnership/ib/'
      path: '/partnership/ib'
      fullPath: '/partnership/ib/'
      preLoaderRoute: typeof withHeaderFooterPartnershipIbIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/affiliate/': {
      id: '/(with-header-footer)/partnership/affiliate/'
      path: '/partnership/affiliate'
      fullPath: '/partnership/affiliate/'
      preLoaderRoute: typeof withHeaderFooterPartnershipAffiliateIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/education/webinars/': {
      id: '/(with-header-footer)/education/webinars/'
      path: '/education/webinars'
      fullPath: '/education/webinars/'
      preLoaderRoute: typeof withHeaderFooterEducationWebinarsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/education/guides/': {
      id: '/(with-header-footer)/education/guides/'
      path: '/education/guides'
      fullPath: '/education/guides/'
      preLoaderRoute: typeof withHeaderFooterEducationGuidesIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/news/': {
      id: '/(with-header-footer)/company/news/'
      path: '/company/news'
      fullPath: '/company/news/'
      preLoaderRoute: typeof withHeaderFooterCompanyNewsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/awards/': {
      id: '/(with-header-footer)/company/awards/'
      path: '/company/awards'
      fullPath: '/company/awards/'
      preLoaderRoute: typeof withHeaderFooterCompanyAwardsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/about/': {
      id: '/(with-header-footer)/company/about/'
      path: '/company/about'
      fullPath: '/company/about/'
      preLoaderRoute: typeof withHeaderFooterCompanyAboutIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
  }
}

interface withHeaderFooterRouteRouteChildren {
  withHeaderFooterIndexRoute: typeof withHeaderFooterIndexRoute
  withHeaderFooterCompanyIndexRoute: typeof withHeaderFooterCompanyIndexRoute
  withHeaderFooterEducationIndexRoute: typeof withHeaderFooterEducationIndexRoute
  withHeaderFooterPartnershipIndexRoute: typeof withHeaderFooterPartnershipIndexRoute
  withHeaderFooterPromotionsIndexRoute: typeof withHeaderFooterPromotionsIndexRoute
  withHeaderFooterToolsIndexRoute: typeof withHeaderFooterToolsIndexRoute
  withHeaderFooterTradingIndexRoute: typeof withHeaderFooterTradingIndexRoute
  withHeaderFooterCompanyAboutIndexRoute: typeof withHeaderFooterCompanyAboutIndexRoute
  withHeaderFooterCompanyAwardsIndexRoute: typeof withHeaderFooterCompanyAwardsIndexRoute
  withHeaderFooterCompanyNewsIndexRoute: typeof withHeaderFooterCompanyNewsIndexRoute
  withHeaderFooterEducationGuidesIndexRoute: typeof withHeaderFooterEducationGuidesIndexRoute
  withHeaderFooterEducationWebinarsIndexRoute: typeof withHeaderFooterEducationWebinarsIndexRoute
  withHeaderFooterPartnershipAffiliateIndexRoute: typeof withHeaderFooterPartnershipAffiliateIndexRoute
  withHeaderFooterPartnershipIbIndexRoute: typeof withHeaderFooterPartnershipIbIndexRoute
  withHeaderFooterTradingAccountsIndexRoute: typeof withHeaderFooterTradingAccountsIndexRoute
  withHeaderFooterTradingInstrumentsIndexRoute: typeof withHeaderFooterTradingInstrumentsIndexRoute
  withHeaderFooterTradingPlatformsIndexRoute: typeof withHeaderFooterTradingPlatformsIndexRoute
  withHeaderFooterTradingSyntxIndexRoute: typeof withHeaderFooterTradingSyntxIndexRoute
}

const withHeaderFooterRouteRouteChildren: withHeaderFooterRouteRouteChildren = {
  withHeaderFooterIndexRoute: withHeaderFooterIndexRoute,
  withHeaderFooterCompanyIndexRoute: withHeaderFooterCompanyIndexRoute,
  withHeaderFooterEducationIndexRoute: withHeaderFooterEducationIndexRoute,
  withHeaderFooterPartnershipIndexRoute: withHeaderFooterPartnershipIndexRoute,
  withHeaderFooterPromotionsIndexRoute: withHeaderFooterPromotionsIndexRoute,
  withHeaderFooterToolsIndexRoute: withHeaderFooterToolsIndexRoute,
  withHeaderFooterTradingIndexRoute: withHeaderFooterTradingIndexRoute,
  withHeaderFooterCompanyAboutIndexRoute:
    withHeaderFooterCompanyAboutIndexRoute,
  withHeaderFooterCompanyAwardsIndexRoute:
    withHeaderFooterCompanyAwardsIndexRoute,
  withHeaderFooterCompanyNewsIndexRoute: withHeaderFooterCompanyNewsIndexRoute,
  withHeaderFooterEducationGuidesIndexRoute:
    withHeaderFooterEducationGuidesIndexRoute,
  withHeaderFooterEducationWebinarsIndexRoute:
    withHeaderFooterEducationWebinarsIndexRoute,
  withHeaderFooterPartnershipAffiliateIndexRoute:
    withHeaderFooterPartnershipAffiliateIndexRoute,
  withHeaderFooterPartnershipIbIndexRoute:
    withHeaderFooterPartnershipIbIndexRoute,
  withHeaderFooterTradingAccountsIndexRoute:
    withHeaderFooterTradingAccountsIndexRoute,
  withHeaderFooterTradingInstrumentsIndexRoute:
    withHeaderFooterTradingInstrumentsIndexRoute,
  withHeaderFooterTradingPlatformsIndexRoute:
    withHeaderFooterTradingPlatformsIndexRoute,
  withHeaderFooterTradingSyntxIndexRoute:
    withHeaderFooterTradingSyntxIndexRoute,
}

const withHeaderFooterRouteRouteWithChildren =
  withHeaderFooterRouteRoute._addFileChildren(
    withHeaderFooterRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  withHeaderFooterRouteRoute: withHeaderFooterRouteRouteWithChildren,
  SigninIndexRoute: SigninIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  withoutHeaderFooterCookiePolicyIndexRoute:
    withoutHeaderFooterCookiePolicyIndexRoute,
  withoutHeaderFooterPrivacyPolicyIndexRoute:
    withoutHeaderFooterPrivacyPolicyIndexRoute,
  withoutHeaderFooterTermsOfServiceIndexRoute:
    withoutHeaderFooterTermsOfServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
