/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as withHeaderFooterRouteRouteImport } from './routes/(with-header-footer)/route'
import { Route as withHeaderFooterIndexRouteImport } from './routes/(with-header-footer)/index'
import { Route as withoutHeaderFooterauthenticatedRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/route'
import { Route as withHeaderFooterCompanyIndexRouteImport } from './routes/(with-header-footer)/company/index'
import { Route as withHeaderFooterPartnershipIndexRouteImport } from './routes/(with-header-footer)/partnership/index'
import { Route as withHeaderFooterToolsIndexRouteImport } from './routes/(with-header-footer)/tools/index'
import { Route as withHeaderFooterTradingIndexRouteImport } from './routes/(with-header-footer)/trading/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/route'
import { Route as withoutHeaderFooterauthenticatednewUserRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/(new-user)/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as withHeaderFooterCompanyAboutIndexRouteImport } from './routes/(with-header-footer)/company/about/index'
import { Route as withHeaderFooterCompanyAwardsIndexRouteImport } from './routes/(with-header-footer)/company/awards/index'
import { Route as withHeaderFooterCompanyNewsIndexRouteImport } from './routes/(with-header-footer)/company/news/index'
import { Route as withHeaderFooterPartnershipAffiliateIndexRouteImport } from './routes/(with-header-footer)/partnership/affiliate/index'
import { Route as withHeaderFooterPartnershipIbIndexRouteImport } from './routes/(with-header-footer)/partnership/ib/index'
import { Route as withHeaderFooterTradingAccountsIndexRouteImport } from './routes/(with-header-footer)/trading/accounts/index'
import { Route as withHeaderFooterTradingInstrumentsIndexRouteImport } from './routes/(with-header-footer)/trading/instruments/index'
import { Route as withHeaderFooterTradingPlatformsIndexRouteImport } from './routes/(with-header-footer)/trading/platforms/index'
import { Route as withHeaderFooterTradingSyntxIndexRouteImport } from './routes/(with-header-footer)/trading/syntx/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/route'
import { Route as withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(basic)/route'
import { Route as withoutHeaderFooterauthenticatedRedirectSigninIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/redirect-signin/index'
import { Route as withoutHeaderFooterguestSigninIndexRouteImport } from './routes/(without-header-footer)/(guest)/signin/index'
import { Route as withoutHeaderFooterleagalPagesCookiePolicyIndexRouteImport } from './routes/(without-header-footer)/(leagal-pages)/cookie-policy/index'
import { Route as withoutHeaderFooterleagalPagesPrivacyPolicyIndexRouteImport } from './routes/(without-header-footer)/(leagal-pages)/privacy-policy/index'
import { Route as withoutHeaderFooterleagalPagesTermsOfServiceIndexRouteImport } from './routes/(without-header-footer)/(leagal-pages)/terms-of-service/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserDashboardIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/dashboard/index'
import { Route as withoutHeaderFooterauthenticatednewUserWelcomeIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(new-user)/welcome/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/deposits/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/message/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-plans/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-sesions/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/withdraws/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(basic)/mining/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(basic)/referral/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(basic)/support-chat/index'
import { Route as withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(basic)/wallet/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/index'
import { Route as withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRouteImport } from './routes/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/wallet/index'

const withHeaderFooterRouteRoute = withHeaderFooterRouteRouteImport.update({
  id: '/(with-header-footer)',
  getParentRoute: () => rootRouteImport,
} as any)
const withHeaderFooterIndexRoute = withHeaderFooterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => withHeaderFooterRouteRoute,
} as any)
const withoutHeaderFooterauthenticatedRouteRoute =
  withoutHeaderFooterauthenticatedRouteRouteImport.update({
    id: '/(without-header-footer)/(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const withHeaderFooterCompanyIndexRoute =
  withHeaderFooterCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipIndexRoute =
  withHeaderFooterPartnershipIndexRouteImport.update({
    id: '/partnership/',
    path: '/partnership/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterToolsIndexRoute =
  withHeaderFooterToolsIndexRouteImport.update({
    id: '/tools/',
    path: '/tools/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingIndexRoute =
  withHeaderFooterTradingIndexRouteImport.update({
    id: '/trading/',
    path: '/trading/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserRouteRoute =
  withoutHeaderFooterauthenticatedexistingUserRouteRouteImport.update({
    id: '/(existing-user)',
    getParentRoute: () => withoutHeaderFooterauthenticatedRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatednewUserRouteRoute =
  withoutHeaderFooterauthenticatednewUserRouteRouteImport.update({
    id: '/(new-user)',
    getParentRoute: () => withoutHeaderFooterauthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const withHeaderFooterCompanyAboutIndexRoute =
  withHeaderFooterCompanyAboutIndexRouteImport.update({
    id: '/company/about/',
    path: '/company/about/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyAwardsIndexRoute =
  withHeaderFooterCompanyAwardsIndexRouteImport.update({
    id: '/company/awards/',
    path: '/company/awards/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterCompanyNewsIndexRoute =
  withHeaderFooterCompanyNewsIndexRouteImport.update({
    id: '/company/news/',
    path: '/company/news/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipAffiliateIndexRoute =
  withHeaderFooterPartnershipAffiliateIndexRouteImport.update({
    id: '/partnership/affiliate/',
    path: '/partnership/affiliate/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterPartnershipIbIndexRoute =
  withHeaderFooterPartnershipIbIndexRouteImport.update({
    id: '/partnership/ib/',
    path: '/partnership/ib/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingAccountsIndexRoute =
  withHeaderFooterTradingAccountsIndexRouteImport.update({
    id: '/trading/accounts/',
    path: '/trading/accounts/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingInstrumentsIndexRoute =
  withHeaderFooterTradingInstrumentsIndexRouteImport.update({
    id: '/trading/instruments/',
    path: '/trading/instruments/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingPlatformsIndexRoute =
  withHeaderFooterTradingPlatformsIndexRouteImport.update({
    id: '/trading/platforms/',
    path: '/trading/platforms/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withHeaderFooterTradingSyntxIndexRoute =
  withHeaderFooterTradingSyntxIndexRouteImport.update({
    id: '/trading/syntx/',
    path: '/trading/syntx/',
    getParentRoute: () => withHeaderFooterRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUseradminRouteRoute =
  withoutHeaderFooterauthenticatedexistingUseradminRouteRouteImport.update({
    id: '/(admin)',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute =
  withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteImport.update({
    id: '/(basic)',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedRedirectSigninIndexRoute =
  withoutHeaderFooterauthenticatedRedirectSigninIndexRouteImport.update({
    id: '/redirect-signin/',
    path: '/redirect-signin/',
    getParentRoute: () => withoutHeaderFooterauthenticatedRouteRoute,
  } as any)
const withoutHeaderFooterguestSigninIndexRoute =
  withoutHeaderFooterguestSigninIndexRouteImport.update({
    id: '/(without-header-footer)/(guest)/signin/',
    path: '/signin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterleagalPagesCookiePolicyIndexRoute =
  withoutHeaderFooterleagalPagesCookiePolicyIndexRouteImport.update({
    id: '/(without-header-footer)/(leagal-pages)/cookie-policy/',
    path: '/cookie-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute =
  withoutHeaderFooterleagalPagesPrivacyPolicyIndexRouteImport.update({
    id: '/(without-header-footer)/(leagal-pages)/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute =
  withoutHeaderFooterleagalPagesTermsOfServiceIndexRouteImport.update({
    id: '/(without-header-footer)/(leagal-pages)/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => rootRouteImport,
  } as any)
const withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () =>
      withoutHeaderFooterauthenticatedexistingUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute =
  withoutHeaderFooterauthenticatednewUserWelcomeIndexRouteImport.update({
    id: '/welcome/',
    path: '/welcome/',
    getParentRoute: () => withoutHeaderFooterauthenticatednewUserRouteRoute,
  } as any)
const withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRouteImport.update(
    {
      id: '/deposits/',
      path: '/deposits/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRouteImport.update(
    {
      id: '/message/',
      path: '/message/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRouteImport.update(
    {
      id: '/mining-plans/',
      path: '/mining-plans/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRouteImport.update(
    {
      id: '/mining-sesions/',
      path: '/mining-sesions/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRouteImport.update(
    {
      id: '/users/',
      path: '/users/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRouteImport.update(
    {
      id: '/withdraws/',
      path: '/withdraws/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRouteImport.update(
    {
      id: '/mining/',
      path: '/mining/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRouteImport.update(
    {
      id: '/referral/',
      path: '/referral/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRouteImport.update(
    {
      id: '/support-chat/',
      path: '/support-chat/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute =
  withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRouteImport.update(
    {
      id: '/wallet/',
      path: '/wallet/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRouteImport.update(
    {
      id: '/users/$userId/',
      path: '/users/$userId/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )
const withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute =
  withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRouteImport.update(
    {
      id: '/users/$userId/wallet/',
      path: '/users/$userId/wallet/',
      getParentRoute: () =>
        withoutHeaderFooterauthenticatedexistingUseradminRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof withHeaderFooterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/company/': typeof withHeaderFooterCompanyIndexRoute
  '/partnership/': typeof withHeaderFooterPartnershipIndexRoute
  '/tools/': typeof withHeaderFooterToolsIndexRoute
  '/trading/': typeof withHeaderFooterTradingIndexRoute
  '/company/about/': typeof withHeaderFooterCompanyAboutIndexRoute
  '/company/awards/': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/company/news/': typeof withHeaderFooterCompanyNewsIndexRoute
  '/partnership/affiliate/': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/partnership/ib/': typeof withHeaderFooterPartnershipIbIndexRoute
  '/trading/accounts/': typeof withHeaderFooterTradingAccountsIndexRoute
  '/trading/instruments/': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/trading/platforms/': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/trading/syntx/': typeof withHeaderFooterTradingSyntxIndexRoute
  '/redirect-signin/': typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  '/signin/': typeof withoutHeaderFooterguestSigninIndexRoute
  '/cookie-policy/': typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  '/privacy-policy/': typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
  '/dashboard/': typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  '/welcome/': typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
  '/deposits/': typeof withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute
  '/message/': typeof withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute
  '/mining-plans/': typeof withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute
  '/mining-sesions/': typeof withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute
  '/users/': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute
  '/withdraws/': typeof withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute
  '/mining/': typeof withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute
  '/referral/': typeof withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute
  '/support-chat/': typeof withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute
  '/wallet/': typeof withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute
  '/users/$userId/': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute
  '/users/$userId/wallet/': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof withHeaderFooterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/company': typeof withHeaderFooterCompanyIndexRoute
  '/partnership': typeof withHeaderFooterPartnershipIndexRoute
  '/tools': typeof withHeaderFooterToolsIndexRoute
  '/trading': typeof withHeaderFooterTradingIndexRoute
  '/company/about': typeof withHeaderFooterCompanyAboutIndexRoute
  '/company/awards': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/company/news': typeof withHeaderFooterCompanyNewsIndexRoute
  '/partnership/affiliate': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/partnership/ib': typeof withHeaderFooterPartnershipIbIndexRoute
  '/trading/accounts': typeof withHeaderFooterTradingAccountsIndexRoute
  '/trading/instruments': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/trading/platforms': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/trading/syntx': typeof withHeaderFooterTradingSyntxIndexRoute
  '/redirect-signin': typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  '/signin': typeof withoutHeaderFooterguestSigninIndexRoute
  '/cookie-policy': typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  '/privacy-policy': typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  '/terms-of-service': typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
  '/dashboard': typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  '/welcome': typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
  '/deposits': typeof withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute
  '/message': typeof withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute
  '/mining-plans': typeof withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute
  '/mining-sesions': typeof withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute
  '/users': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute
  '/withdraws': typeof withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute
  '/mining': typeof withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute
  '/referral': typeof withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute
  '/support-chat': typeof withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute
  '/wallet': typeof withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute
  '/users/$userId': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute
  '/users/$userId/wallet': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(with-header-footer)': typeof withHeaderFooterRouteRouteWithChildren
  '/(without-header-footer)/(authenticated)': typeof withoutHeaderFooterauthenticatedRouteRouteWithChildren
  '/(with-header-footer)/': typeof withHeaderFooterIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)': typeof withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren
  '/(without-header-footer)/(authenticated)/(new-user)': typeof withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(with-header-footer)/company/': typeof withHeaderFooterCompanyIndexRoute
  '/(with-header-footer)/partnership/': typeof withHeaderFooterPartnershipIndexRoute
  '/(with-header-footer)/tools/': typeof withHeaderFooterToolsIndexRoute
  '/(with-header-footer)/trading/': typeof withHeaderFooterTradingIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)': typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRouteWithChildren
  '/(without-header-footer)/(authenticated)/(existing-user)/(basic)': typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteWithChildren
  '/(with-header-footer)/company/about/': typeof withHeaderFooterCompanyAboutIndexRoute
  '/(with-header-footer)/company/awards/': typeof withHeaderFooterCompanyAwardsIndexRoute
  '/(with-header-footer)/company/news/': typeof withHeaderFooterCompanyNewsIndexRoute
  '/(with-header-footer)/partnership/affiliate/': typeof withHeaderFooterPartnershipAffiliateIndexRoute
  '/(with-header-footer)/partnership/ib/': typeof withHeaderFooterPartnershipIbIndexRoute
  '/(with-header-footer)/trading/accounts/': typeof withHeaderFooterTradingAccountsIndexRoute
  '/(with-header-footer)/trading/instruments/': typeof withHeaderFooterTradingInstrumentsIndexRoute
  '/(with-header-footer)/trading/platforms/': typeof withHeaderFooterTradingPlatformsIndexRoute
  '/(with-header-footer)/trading/syntx/': typeof withHeaderFooterTradingSyntxIndexRoute
  '/(without-header-footer)/(authenticated)/redirect-signin/': typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
  '/(without-header-footer)/(guest)/signin/': typeof withoutHeaderFooterguestSigninIndexRoute
  '/(without-header-footer)/(leagal-pages)/cookie-policy/': typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  '/(without-header-footer)/(leagal-pages)/privacy-policy/': typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  '/(without-header-footer)/(leagal-pages)/terms-of-service/': typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/': typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
  '/(without-header-footer)/(authenticated)/(new-user)/welcome/': typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/deposits/': typeof withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/message/': typeof withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-plans/': typeof withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-sesions/': typeof withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/withdraws/': typeof withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/mining/': typeof withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/referral/': typeof withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/support-chat/': typeof withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/wallet/': typeof withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute
  '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/wallet/': typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/company/'
    | '/partnership/'
    | '/tools/'
    | '/trading/'
    | '/company/about/'
    | '/company/awards/'
    | '/company/news/'
    | '/partnership/affiliate/'
    | '/partnership/ib/'
    | '/trading/accounts/'
    | '/trading/instruments/'
    | '/trading/platforms/'
    | '/trading/syntx/'
    | '/redirect-signin/'
    | '/signin/'
    | '/cookie-policy/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/dashboard/'
    | '/welcome/'
    | '/deposits/'
    | '/message/'
    | '/mining-plans/'
    | '/mining-sesions/'
    | '/users/'
    | '/withdraws/'
    | '/mining/'
    | '/referral/'
    | '/support-chat/'
    | '/wallet/'
    | '/users/$userId/'
    | '/users/$userId/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/company'
    | '/partnership'
    | '/tools'
    | '/trading'
    | '/company/about'
    | '/company/awards'
    | '/company/news'
    | '/partnership/affiliate'
    | '/partnership/ib'
    | '/trading/accounts'
    | '/trading/instruments'
    | '/trading/platforms'
    | '/trading/syntx'
    | '/redirect-signin'
    | '/signin'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard'
    | '/welcome'
    | '/deposits'
    | '/message'
    | '/mining-plans'
    | '/mining-sesions'
    | '/users'
    | '/withdraws'
    | '/mining'
    | '/referral'
    | '/support-chat'
    | '/wallet'
    | '/users/$userId'
    | '/users/$userId/wallet'
  id:
    | '__root__'
    | '/(with-header-footer)'
    | '/(without-header-footer)/(authenticated)'
    | '/(with-header-footer)/'
    | '/(without-header-footer)/(authenticated)/(existing-user)'
    | '/(without-header-footer)/(authenticated)/(new-user)'
    | '/api/auth/$'
    | '/(with-header-footer)/company/'
    | '/(with-header-footer)/partnership/'
    | '/(with-header-footer)/tools/'
    | '/(with-header-footer)/trading/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(basic)'
    | '/(with-header-footer)/company/about/'
    | '/(with-header-footer)/company/awards/'
    | '/(with-header-footer)/company/news/'
    | '/(with-header-footer)/partnership/affiliate/'
    | '/(with-header-footer)/partnership/ib/'
    | '/(with-header-footer)/trading/accounts/'
    | '/(with-header-footer)/trading/instruments/'
    | '/(with-header-footer)/trading/platforms/'
    | '/(with-header-footer)/trading/syntx/'
    | '/(without-header-footer)/(authenticated)/redirect-signin/'
    | '/(without-header-footer)/(guest)/signin/'
    | '/(without-header-footer)/(leagal-pages)/cookie-policy/'
    | '/(without-header-footer)/(leagal-pages)/privacy-policy/'
    | '/(without-header-footer)/(leagal-pages)/terms-of-service/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/'
    | '/(without-header-footer)/(authenticated)/(new-user)/welcome/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/deposits/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/message/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-plans/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-sesions/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/withdraws/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/mining/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/referral/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/support-chat/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/wallet/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/'
    | '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  withHeaderFooterRouteRoute: typeof withHeaderFooterRouteRouteWithChildren
  withoutHeaderFooterauthenticatedRouteRoute: typeof withoutHeaderFooterauthenticatedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  withoutHeaderFooterguestSigninIndexRoute: typeof withoutHeaderFooterguestSigninIndexRoute
  withoutHeaderFooterleagalPagesCookiePolicyIndexRoute: typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRoute
  withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute: typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute
  withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute: typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(with-header-footer)': {
      id: '/(with-header-footer)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withHeaderFooterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/': {
      id: '/(with-header-footer)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof withHeaderFooterIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(without-header-footer)/(authenticated)': {
      id: '/(without-header-footer)/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/company/': {
      id: '/(with-header-footer)/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof withHeaderFooterCompanyIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/': {
      id: '/(with-header-footer)/partnership/'
      path: '/partnership'
      fullPath: '/partnership/'
      preLoaderRoute: typeof withHeaderFooterPartnershipIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/tools/': {
      id: '/(with-header-footer)/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof withHeaderFooterToolsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/': {
      id: '/(with-header-footer)/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof withHeaderFooterTradingIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(new-user)': {
      id: '/(without-header-footer)/(authenticated)/(new-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatednewUserRouteRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with-header-footer)/company/about/': {
      id: '/(with-header-footer)/company/about/'
      path: '/company/about'
      fullPath: '/company/about/'
      preLoaderRoute: typeof withHeaderFooterCompanyAboutIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/awards/': {
      id: '/(with-header-footer)/company/awards/'
      path: '/company/awards'
      fullPath: '/company/awards/'
      preLoaderRoute: typeof withHeaderFooterCompanyAwardsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/company/news/': {
      id: '/(with-header-footer)/company/news/'
      path: '/company/news'
      fullPath: '/company/news/'
      preLoaderRoute: typeof withHeaderFooterCompanyNewsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/affiliate/': {
      id: '/(with-header-footer)/partnership/affiliate/'
      path: '/partnership/affiliate'
      fullPath: '/partnership/affiliate/'
      preLoaderRoute: typeof withHeaderFooterPartnershipAffiliateIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/partnership/ib/': {
      id: '/(with-header-footer)/partnership/ib/'
      path: '/partnership/ib'
      fullPath: '/partnership/ib/'
      preLoaderRoute: typeof withHeaderFooterPartnershipIbIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/accounts/': {
      id: '/(with-header-footer)/trading/accounts/'
      path: '/trading/accounts'
      fullPath: '/trading/accounts/'
      preLoaderRoute: typeof withHeaderFooterTradingAccountsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/instruments/': {
      id: '/(with-header-footer)/trading/instruments/'
      path: '/trading/instruments'
      fullPath: '/trading/instruments/'
      preLoaderRoute: typeof withHeaderFooterTradingInstrumentsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/platforms/': {
      id: '/(with-header-footer)/trading/platforms/'
      path: '/trading/platforms'
      fullPath: '/trading/platforms/'
      preLoaderRoute: typeof withHeaderFooterTradingPlatformsIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(with-header-footer)/trading/syntx/': {
      id: '/(with-header-footer)/trading/syntx/'
      path: '/trading/syntx'
      fullPath: '/trading/syntx/'
      preLoaderRoute: typeof withHeaderFooterTradingSyntxIndexRouteImport
      parentRoute: typeof withHeaderFooterRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(basic)': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(basic)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/redirect-signin/': {
      id: '/(without-header-footer)/(authenticated)/redirect-signin/'
      path: '/redirect-signin'
      fullPath: '/redirect-signin/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedRouteRoute
    }
    '/(without-header-footer)/(guest)/signin/': {
      id: '/(without-header-footer)/(guest)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof withoutHeaderFooterguestSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(leagal-pages)/cookie-policy/': {
      id: '/(without-header-footer)/(leagal-pages)/cookie-policy/'
      path: '/cookie-policy'
      fullPath: '/cookie-policy/'
      preLoaderRoute: typeof withoutHeaderFooterleagalPagesCookiePolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(leagal-pages)/privacy-policy/': {
      id: '/(without-header-footer)/(leagal-pages)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof withoutHeaderFooterleagalPagesPrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(leagal-pages)/terms-of-service/': {
      id: '/(without-header-footer)/(leagal-pages)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof withoutHeaderFooterleagalPagesTermsOfServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(new-user)/welcome/': {
      id: '/(without-header-footer)/(authenticated)/(new-user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatednewUserRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/deposits/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/deposits/'
      path: '/deposits'
      fullPath: '/deposits/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/message/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/message/'
      path: '/message'
      fullPath: '/message/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-plans/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-plans/'
      path: '/mining-plans'
      fullPath: '/mining-plans/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-sesions/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/mining-sesions/'
      path: '/mining-sesions'
      fullPath: '/mining-sesions/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/withdraws/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/withdraws/'
      path: '/withdraws'
      fullPath: '/withdraws/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/mining/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/mining/'
      path: '/mining'
      fullPath: '/mining/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/referral/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/referral/'
      path: '/referral'
      fullPath: '/referral/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/support-chat/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/support-chat/'
      path: '/support-chat'
      fullPath: '/support-chat/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/wallet/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(basic)/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
    '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/wallet/': {
      id: '/(without-header-footer)/(authenticated)/(existing-user)/(admin)/users/$userId/wallet/'
      path: '/users/$userId/wallet'
      fullPath: '/users/$userId/wallet/'
      preLoaderRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRouteImport
      parentRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRoute
    }
  }
}

interface withHeaderFooterRouteRouteChildren {
  withHeaderFooterIndexRoute: typeof withHeaderFooterIndexRoute
  withHeaderFooterCompanyIndexRoute: typeof withHeaderFooterCompanyIndexRoute
  withHeaderFooterPartnershipIndexRoute: typeof withHeaderFooterPartnershipIndexRoute
  withHeaderFooterToolsIndexRoute: typeof withHeaderFooterToolsIndexRoute
  withHeaderFooterTradingIndexRoute: typeof withHeaderFooterTradingIndexRoute
  withHeaderFooterCompanyAboutIndexRoute: typeof withHeaderFooterCompanyAboutIndexRoute
  withHeaderFooterCompanyAwardsIndexRoute: typeof withHeaderFooterCompanyAwardsIndexRoute
  withHeaderFooterCompanyNewsIndexRoute: typeof withHeaderFooterCompanyNewsIndexRoute
  withHeaderFooterPartnershipAffiliateIndexRoute: typeof withHeaderFooterPartnershipAffiliateIndexRoute
  withHeaderFooterPartnershipIbIndexRoute: typeof withHeaderFooterPartnershipIbIndexRoute
  withHeaderFooterTradingAccountsIndexRoute: typeof withHeaderFooterTradingAccountsIndexRoute
  withHeaderFooterTradingInstrumentsIndexRoute: typeof withHeaderFooterTradingInstrumentsIndexRoute
  withHeaderFooterTradingPlatformsIndexRoute: typeof withHeaderFooterTradingPlatformsIndexRoute
  withHeaderFooterTradingSyntxIndexRoute: typeof withHeaderFooterTradingSyntxIndexRoute
}

const withHeaderFooterRouteRouteChildren: withHeaderFooterRouteRouteChildren = {
  withHeaderFooterIndexRoute: withHeaderFooterIndexRoute,
  withHeaderFooterCompanyIndexRoute: withHeaderFooterCompanyIndexRoute,
  withHeaderFooterPartnershipIndexRoute: withHeaderFooterPartnershipIndexRoute,
  withHeaderFooterToolsIndexRoute: withHeaderFooterToolsIndexRoute,
  withHeaderFooterTradingIndexRoute: withHeaderFooterTradingIndexRoute,
  withHeaderFooterCompanyAboutIndexRoute:
    withHeaderFooterCompanyAboutIndexRoute,
  withHeaderFooterCompanyAwardsIndexRoute:
    withHeaderFooterCompanyAwardsIndexRoute,
  withHeaderFooterCompanyNewsIndexRoute: withHeaderFooterCompanyNewsIndexRoute,
  withHeaderFooterPartnershipAffiliateIndexRoute:
    withHeaderFooterPartnershipAffiliateIndexRoute,
  withHeaderFooterPartnershipIbIndexRoute:
    withHeaderFooterPartnershipIbIndexRoute,
  withHeaderFooterTradingAccountsIndexRoute:
    withHeaderFooterTradingAccountsIndexRoute,
  withHeaderFooterTradingInstrumentsIndexRoute:
    withHeaderFooterTradingInstrumentsIndexRoute,
  withHeaderFooterTradingPlatformsIndexRoute:
    withHeaderFooterTradingPlatformsIndexRoute,
  withHeaderFooterTradingSyntxIndexRoute:
    withHeaderFooterTradingSyntxIndexRoute,
}

const withHeaderFooterRouteRouteWithChildren =
  withHeaderFooterRouteRoute._addFileChildren(
    withHeaderFooterRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatedexistingUseradminRouteRouteChildren {
  withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute
  withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute
}

const withoutHeaderFooterauthenticatedexistingUseradminRouteRouteChildren: withoutHeaderFooterauthenticatedexistingUseradminRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminDepositsIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminMessageIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminMiningPlansIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminMiningSesionsIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminUsersIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminWithdrawsIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdIndexRoute,
    withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute:
      withoutHeaderFooterauthenticatedexistingUseradminUsersUserIdWalletIndexRoute,
  }

const withoutHeaderFooterauthenticatedexistingUseradminRouteRouteWithChildren =
  withoutHeaderFooterauthenticatedexistingUseradminRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatedexistingUseradminRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteChildren {
  withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute
  withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute
  withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute
  withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute
}

const withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteChildren: withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserbasicMiningIndexRoute,
    withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserbasicReferralIndexRoute,
    withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserbasicSupportChatIndexRoute,
    withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserbasicWalletIndexRoute,
  }

const withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteWithChildren =
  withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren {
  withoutHeaderFooterauthenticatedexistingUseradminRouteRoute: typeof withoutHeaderFooterauthenticatedexistingUseradminRouteRouteWithChildren
  withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute: typeof withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteWithChildren
  withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute: typeof withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute
}

const withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren: withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatedexistingUseradminRouteRoute:
      withoutHeaderFooterauthenticatedexistingUseradminRouteRouteWithChildren,
    withoutHeaderFooterauthenticatedexistingUserbasicRouteRoute:
      withoutHeaderFooterauthenticatedexistingUserbasicRouteRouteWithChildren,
    withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute:
      withoutHeaderFooterauthenticatedexistingUserDashboardIndexRoute,
  }

const withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren =
  withoutHeaderFooterauthenticatedexistingUserRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatedexistingUserRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatednewUserRouteRouteChildren {
  withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute: typeof withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute
}

const withoutHeaderFooterauthenticatednewUserRouteRouteChildren: withoutHeaderFooterauthenticatednewUserRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute:
      withoutHeaderFooterauthenticatednewUserWelcomeIndexRoute,
  }

const withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren =
  withoutHeaderFooterauthenticatednewUserRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatednewUserRouteRouteChildren,
  )

interface withoutHeaderFooterauthenticatedRouteRouteChildren {
  withoutHeaderFooterauthenticatedexistingUserRouteRoute: typeof withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren
  withoutHeaderFooterauthenticatednewUserRouteRoute: typeof withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren
  withoutHeaderFooterauthenticatedRedirectSigninIndexRoute: typeof withoutHeaderFooterauthenticatedRedirectSigninIndexRoute
}

const withoutHeaderFooterauthenticatedRouteRouteChildren: withoutHeaderFooterauthenticatedRouteRouteChildren =
  {
    withoutHeaderFooterauthenticatedexistingUserRouteRoute:
      withoutHeaderFooterauthenticatedexistingUserRouteRouteWithChildren,
    withoutHeaderFooterauthenticatednewUserRouteRoute:
      withoutHeaderFooterauthenticatednewUserRouteRouteWithChildren,
    withoutHeaderFooterauthenticatedRedirectSigninIndexRoute:
      withoutHeaderFooterauthenticatedRedirectSigninIndexRoute,
  }

const withoutHeaderFooterauthenticatedRouteRouteWithChildren =
  withoutHeaderFooterauthenticatedRouteRoute._addFileChildren(
    withoutHeaderFooterauthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  withHeaderFooterRouteRoute: withHeaderFooterRouteRouteWithChildren,
  withoutHeaderFooterauthenticatedRouteRoute:
    withoutHeaderFooterauthenticatedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  withoutHeaderFooterguestSigninIndexRoute:
    withoutHeaderFooterguestSigninIndexRoute,
  withoutHeaderFooterleagalPagesCookiePolicyIndexRoute:
    withoutHeaderFooterleagalPagesCookiePolicyIndexRoute,
  withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute:
    withoutHeaderFooterleagalPagesPrivacyPolicyIndexRoute,
  withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute:
    withoutHeaderFooterleagalPagesTermsOfServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
