import {
  mysqlTable,
  int,
  varchar,
  mysqlEnum,
  char,
  timestamp,
  float,
  tinyint,
  smallint,
  boolean,
  foreignKey,
} from "drizzle-orm/mysql-core";
import { id } from "@repo/utils/id";
import { relations } from "drizzle-orm";

// -------------------------
// UserTable
// -------------------------

export const UserTable = mysqlTable(
  "users",
  {
    id: autogeneratedId(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    fullName: varchar("full_name", { length: 255 }).notNull(),
    avatarUrl: varchar("avatar_url", { length: 255 }).notNull(),
    age: int("age").notNull(),
    role: roleEnums()
      .notNull()
      .$default(() => "basic"),
    phoneNumber: char("phone_number", { length: 10 }).notNull(),
    referrerId: char("referrer_id", { length: 10 }),
    userStatus: userStatusEnums("user_status"),

    ...metadata("USER"),
  },

  (table) => [
    foreignKey({
      columns: [table.referrerId],
      foreignColumns: [table.id],
      name: "users_referrer_id_fk",
    })
      .onDelete("set null")
      .onUpdate("cascade"),
  ],
);

export const UserRelations = relations(UserTable, ({ one, many }) => ({
  referredBy: one(UserTable, {
    fields: [UserTable.referrerId],
    references: [UserTable.id],
    relationName: "UserReferrals",
  }),
  referrals: many(UserTable, {
    relationName: "UserReferrals",
  }),
  tradingWallet: one(TradingWalletTable),
  miningWallet: one(MiningWalletTable),
  miningWalletDeposits: many(MiningWalletDepositsTable),
  miningWalletWithdraws: many(MiningWalletWithdrawTable),
  tradingWalletDeposits: many(TradingWalletDepositsTable),
  tradingWalletWithdraws: many(TradingWalletWithdrawTable),
  rating: one(RatingTable),
  miningOrders: many(MiningOrderTable),
  tradingOrders: many(TradingOrderTable),
}));

// -------------------------
// TradingWalletTable
// -------------------------

export const TradingWalletTable = mysqlTable("trading_wallet", {
  id: autogeneratedId(),
  balance: float("balance", { precision: 2 }).$default(() => 0),
  associatedUser: foreignId("associated_user")
    .unique()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadata("TWAL"),
});

export const TradingWalletRelations = relations(
  TradingWalletTable,
  ({ one, many }) => ({
    user: one(UserTable, {
      fields: [TradingWalletTable.associatedUser],
      references: [UserTable.id],
    }),
    deposits: many(TradingWalletDepositsTable),
    withdraws: many(TradingWalletWithdrawTable),
  }),
);

// -------------------------
// MiningWalletTable
// -------------------------

export const MiningWalletTable = mysqlTable("mining_wallet", {
  id: autogeneratedId(),
  balance: float("balance", { precision: 2 }).$default(() => 0),
  associatedUser: foreignId("associated_user")
    .unique()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadata("MWAL"),
});

export const MiningWalletRelations = relations(
  MiningWalletTable,
  ({ one, many }) => ({
    user: one(UserTable, {
      fields: [MiningWalletTable.associatedUser],
      references: [UserTable.id],
    }),
    deposits: many(MiningWalletDepositsTable),
    withdraws: many(MiningWalletWithdrawTable),
  }),
);

// -------------------------
// RatingTable
// -------------------------

export const RatingTable = mysqlTable("rating", {
  id: autogeneratedId(),
  associatedUser: foreignId("associated_user")
    .unique()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),
  ratingStar: tinyint("rating_star_count")
    .$defaultFn(() => 1)
    .notNull(),

  ...metadata("RTNG"),
});

export const RatingRelations = relations(RatingTable, ({ one }) => ({
  user: one(UserTable, {
    fields: [RatingTable.associatedUser],
    references: [UserTable.id],
  }),
}));

// -------------------------
// NewsTable
// -------------------------

export const NewsTable = mysqlTable("news", {
  id: autogeneratedId(),
  effectiveDate: timestamp("effective_date", {
    mode: "date",
    fsp: 6,
  }).notNull(),
  heading: varchar("heading", { length: 255 }).notNull(),
  details: varchar("details", { length: 1023 }).notNull(),

  ...metadata("NEWS"),
});

// -------------------------
// MiningProfileTable
// -------------------------

export const MiningProfileTable = mysqlTable("mining_profile", {
  id: autogeneratedId(),
  maximumAllowedAmount: int("maximum_allowed_amount").notNull(),
  minimumAllowedAmount: int("minimum_allowed_amount").notNull(),
  lockinPeriod: smallint("lockin_period").notNull(),
  category: varchar("category", { length: 50 }).notNull(),
  dailyReturn: float("daily_return", { precision: 2 }).notNull(),
  isPopular: boolean("is_popular")
    .$default(() => false)
    .notNull(),

  ...metadata("MPRO"),
});

export const MiningProfileRelations = relations(
  MiningProfileTable,
  ({ many }) => ({
    orders: many(MiningOrderTable),
  }),
);

// -------------------------
// MiningOrderTable
// -------------------------

export const MiningOrderTable = mysqlTable("mining_order", {
  id: autogeneratedId(),
  orderedBy: foreignId("ordered_by")
    .notNull()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amountInvested: int("amount_invested").notNull(),
  amountReceived: int("amount_received").default(0),
  miningProfileUsed: foreignId("mining_profile_used")
    .notNull()
    .references(() => MiningProfileTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  miningStatus: investmentStatusEnums().$defaultFn(() => "active"),

  ...metadata("MORD"),
});

export const MiningOrderRelations = relations(MiningOrderTable, ({ one }) => ({
  user: one(UserTable, {
    fields: [MiningOrderTable.orderedBy],
    references: [UserTable.id],
  }),
  miningProfile: one(MiningProfileTable, {
    fields: [MiningOrderTable.miningProfileUsed],
    references: [MiningProfileTable.id],
  }),
}));

// -------------------------
// TradingOrderTable
// -------------------------

export const TradingOrderTable = mysqlTable("trading_order", {
  id: autogeneratedId(),
  orderedBy: foreignId("ordered_by")
    .notNull()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amountInvested: int("amount_invested").notNull(),
  amountReceived: int("amount_received").default(0),
  tradingStatus: investmentStatusEnums().$defaultFn(() => "active"),

  ...metadata("TORD"),
});

export const TradingOrderRelations = relations(
  TradingOrderTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [TradingOrderTable.orderedBy],
      references: [UserTable.id],
    }),
  }),
);

// -------------------------
// MiningWalletDepositsTable
// -------------------------

export const MiningWalletDepositsTable = mysqlTable("mining_wallet_deposits", {
  id: autogeneratedId(),
  orderedBy: foreignId("ordered_by")
    .notNull()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  wallet: foreignId("wallet")
    .notNull()
    .references(() => MiningWalletTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amount: int("amount").notNull(),
  status: depositStatusEnums(),
  depositMethod: transactionMethodEnums("deposit_method").notNull(),
  transactionId: varchar("transaction_id", { length: 127 }).notNull(),
  depositProof: varchar("deposit_proof", { length: 255 }).notNull(),

  ...metadata("MWDP"),
});

export const MiningWalletDepositsRelations = relations(
  MiningWalletDepositsTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [MiningWalletDepositsTable.orderedBy],
      references: [UserTable.id],
    }),
    wallet: one(MiningWalletTable, {
      fields: [MiningWalletDepositsTable.wallet],
      references: [MiningWalletTable.id],
    }),
  }),
);

// -------------------------
// TradingWalletDepositsTable
// -------------------------

export const TradingWalletDepositsTable = mysqlTable(
  "trading_wallet_deposits",
  {
    id: autogeneratedId(),
    orderedBy: foreignId("ordered_by")
      .notNull()
      .references(() => UserTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    wallet: foreignId("wallet")
      .notNull()
      .references(() => TradingWalletTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    amount: int("amount").notNull(),
    status: depositStatusEnums(),
    depositMethod: transactionMethodEnums("deposit_method").notNull(),
    transactionId: varchar("transaction_id", { length: 127 }).notNull(),
    depositProof: varchar("deposit_proof", { length: 255 }).notNull(),

    ...metadata("TWDP"),
  },
);

export const TradingWalletDepositsRelations = relations(
  TradingWalletDepositsTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [TradingWalletDepositsTable.orderedBy],
      references: [UserTable.id],
    }),
    wallet: one(TradingWalletTable, {
      fields: [TradingWalletDepositsTable.wallet],
      references: [TradingWalletTable.id],
    }),
  }),
);

// -------------------------
// MiningWalletWithdrawTable
// -------------------------

export const MiningWalletWithdrawTable = mysqlTable("mining_wallet_withdraw", {
  id: autogeneratedId(),
  orderedBy: foreignId("ordered_by")
    .notNull()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  wallet: foreignId("wallet")
    .notNull()
    .references(() => MiningWalletTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amount: int("amount").notNull(),
  cryptoWalletAddress: varchar("crypto_wallet_address", {
    length: 255,
  }).notNull(),
  status: withdrawlStatusEnums(),
  withdrawalMethod: transactionMethodEnums("withdrawal_method").notNull(),

  ...metadata("MWWD"),
});

export const MiningWalletWithdrawRelations = relations(
  MiningWalletWithdrawTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [MiningWalletWithdrawTable.orderedBy],
      references: [UserTable.id],
    }),
    wallet: one(MiningWalletTable, {
      fields: [MiningWalletWithdrawTable.wallet],
      references: [MiningWalletTable.id],
    }),
  }),
);

// -------------------------
// TradingWalletWithdrawTable
// -------------------------

export const TradingWalletWithdrawTable = mysqlTable(
  "trading_wallet_withdraw",
  {
    id: autogeneratedId(),
    orderedBy: foreignId("ordered_by")
      .notNull()
      .references(() => UserTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    wallet: foreignId("wallet")
      .notNull()
      .references(() => TradingWalletTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    amount: int("amount").notNull(),
    cryptoWaletAddress: varchar("crypto_walet_address", {
      length: 255,
    }).notNull(),
    status: withdrawlStatusEnums(),
    withdrawlMethod: transactionMethodEnums("withdrawl_method").notNull(),

    ...metadata("TWWD"),
  },
);

export const TradingWalletWithdrawRelations = relations(
  TradingWalletWithdrawTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [TradingWalletWithdrawTable.orderedBy],
      references: [UserTable.id],
    }),
    wallet: one(TradingWalletTable, {
      fields: [TradingWalletWithdrawTable.wallet],
      references: [TradingWalletTable.id],
    }),
  }),
);

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
export type TableIdentifierToken =
  /**
   * UserTable
   */
  | "USER"
  /**
   * RatingTable
   */
  | "RTNG"
  /**
   * MiningWalletTable
   */
  | "MWAL"
  /**
   * NewsTable
   */
  | "NEWS"
  /**
   * MiningOrderTable
   */
  | "MORD"
  /**
   * TradingOrderTable
   */
  | "TORD"
  /**
   * MiningProfileTable
   */
  | "MPRO"
  /**
   * TradingWalletTable
   */
  | "TWAL"
  /**
   * TradingWalletDepositsTable
   */
  | "TWDP"
  /**
   * TradingWalletWithdrawsTable
   */
  | "TWWD"
  /**
   * MiningWalletDepositsTable
   */
  | "MWDP"
  /**
   * MiningWalletWithdrawTable
   */
  | "MWWD";

export function roleEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "role", ["admin", "basic"]);
}
export function transactionMethodEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "transaction_method", [
    "BSC",
    "TRX",
    "ETH",
    "Bitcoin",
  ]);
}
export function userStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "user_status", [
    "active",
    "inactive",
    "blocked",
  ]).$defaultFn(() => "active");
}
export function investmentStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "investment_status", ["active", "completed"]);
}
export function depositStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "deposit_status", [
    "pending",
    "processed",
    "validating",
    "rejected",
  ]).$defaultFn(() => "pending");
}
export function withdrawlStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "withdrawl_status", [
    "pending",
    "processed",
    "validating",
    "rejected",
  ]);
}
export function updatedAt(columnName?: string) {
  return timestamp(columnName ?? "updated_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
}
export function createdAt(columnName?: string) {
  return timestamp(columnName ?? "created_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
}
export function metadata(token: TableIdentifierToken) {
  return {
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    tableIdentifierToken: tokenColumn(token),
  };
}
export function tableIdentifierToken(columnName?: string) {
  return mysqlEnum(columnName ?? "table_identifier_token", [
    "USER",
    "TWAL",
    "MWAL",
    "RTNG",
    "MORD",
    "NEWS",
    "MPRO",
    "TORD",
    "TWDP",
    "TWWD",
    "MWDP",
    "MWWD",
  ] as [TableIdentifierToken, ...TableIdentifierToken[]]);
}
export function tokenColumn(token: TableIdentifierToken) {
  return tableIdentifierToken().notNull().default(token);
}
export function autogeneratedId() {
  return char("id", { length: 10 })
    .primaryKey()
    .$defaultFn(() => id());
}
export function foreignId(columnName: string) {
  return char(columnName, { length: 10 });
}

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */

const tableMap = {
  USER: "UserTable",
  TWAL: "TradingWalletTable",
  MWAL: "MiningWalletTable",
  NEWS: "NewsTable",
  RTNG: "RatingTable",
  TORD: "TradingOrderTable",
  MORD: "MiningOrderTable",
  MPRO: "MiningProfileTable",
  TWDP: "TradingWalletDepositsTable",
  TWWD: "TradingWalletWithdrawTable",
  MWDP: "MiningWalletDepositsTable",
  MWWD: "MiningWalletWithdrawTable",
} as const;

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 *
 */

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
