import {
  mysqlTable,
  int,
  varchar,
  mysqlEnum,
  char,
  timestamp,
  float,
  tinyint,
  smallint,
  boolean,
  foreignKey,
} from "drizzle-orm/mysql-core";
import { id } from "@repo/utils/id";
import { DEPOSIT_STATUS, INVESTMENT_STATUS, ROLE, TRANSACTION_METHOD, USER_STATUS, WITHDRAWL_STATUS } from "@repo/utils/db-enums";

// -------------------------
// Table__User
// -------------------------

export const Table__User = mysqlTable(
  "user",
  {
    id: autogeneratedId(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    fullName: varchar("full_name", { length: 255 }).notNull(),
    avatarUrl: varchar("avatar_url", { length: 255 }).notNull(),
    age: int("age").notNull(),
    role: roleEnums()
      .notNull()
      .$default(() => "BASIC"),
    phoneNumber: char("phone_number", { length: 10 }).notNull(),
    referrerId: char("referrer_id", { length: 10 }),
    userStatus: userStatusEnums("user_status"),

    ...metadata("USER"),
  },

  (table) => [
    foreignKey({
      columns: [table.referrerId],
      foreignColumns: [table.id],
      name: "users_referrer_id_fk",
    })
      .onDelete("set null")
      .onUpdate("cascade"),
  ],
);

// export const Relations__User = relations(Table__User, ({ one, many }) => ({
//   referredBy: one(Table__User, {
//     fields: [Table__User.referrerId],
//     references: [Table__User.id],
//     relationName: "UserReferrals",
//   }),
//   referrals: many(Table__User, {
//     relationName: "UserReferrals",
//   }),
//   tradingWallet: one(Table__TradingWallet),
//   miningWallet: one(Table__MiningWallet),
//   miningWalletDeposits: many(Table__MiningWalletDeposits),
//   miningWalletWithdraws: many(Table__MiningWalletWithdraw),
//   tradingWalletDeposits: many(Table__TradingWalletDeposits),
//   tradingWalletWithdraws: many(Table__TradingWalletWithdraw),
//   rating: one(Table__Rating),
//   miningOrders: many(Table__MiningOrder),
//   tradingOrders: many(Table__TradingOrder),
// }));

// -------------------------
// Table__TradingWallet
// -------------------------

export const Table__TradingWallet = mysqlTable("trading_wallet", {
  id: autogeneratedId(),
  balance: float("balance", { precision: 2 }).$default(() => 0),
  associatedUser: foreignId("associated_user")
    .unique()
    .references(() => Table__User.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadata("TWAL"),
});

// export const Relations__TradingWallet = relations(
//   Table__TradingWallet,
//   ({ one, many }) => ({
//     user: one(Table__User, {
//       fields: [Table__TradingWallet.associatedUser],
//       references: [Table__User.id],
//     }),
//     deposits: many(Table__TradingWalletDeposits),
//     withdraws: many(Table__TradingWalletWithdraw),
//   }),
// );

// -------------------------
// Table__MiningWallet
// -------------------------

export const Table__MiningWallet = mysqlTable("mining_wallet", {
  id: autogeneratedId(),
  balance: float("balance", { precision: 2 }).$default(() => 0),
  associatedUser: foreignId("associated_user")
    .unique()
    .references(() => Table__User.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadata("MWAL"),
});

// export const Relations__MiningWallet = relations(
//   Table__MiningWallet,
//   ({ one, many }) => ({
//     user: one(Table__User, {
//       fields: [Table__MiningWallet.associatedUser],
//       references: [Table__User.id],
//     }),
//     deposits: many(Table__MiningWalletDeposits),
//     withdraws: many(Table__MiningWalletWithdraw),
//   }),
// );

// -------------------------
// Table__Rating
// -------------------------

export const Table__Rating = mysqlTable("rating", {
  id: autogeneratedId(),
  associatedUser: foreignId("associated_user")
    .unique()
    .references(() => Table__User.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),
  ratingStar: tinyint("rating_star_count")
    .$defaultFn(() => 1)
    .notNull(),

  ...metadata("RTNG"),
});

// export const Relations__Rating = relations(Table__Rating, ({ one }) => ({
//   user: one(Table__User, {
//     fields: [Table__Rating.associatedUser],
//     references: [Table__User.id],
//   }),
// }));

// -------------------------
// Table__News
// -------------------------

export const Table__News = mysqlTable("news", {
  id: autogeneratedId(),
  effectiveDate: timestamp("effective_date", {
    mode: "date",
    fsp: 6,
  }).notNull(),
  heading: varchar("heading", { length: 255 }).notNull(),
  details: varchar("details", { length: 1023 }).notNull(),

  ...metadata("NEWS"),
});

// -------------------------
// Table__MiningProfile
// -------------------------

export const Table__MiningProfile = mysqlTable("mining_profile", {
  id: autogeneratedId(),
  maximumAllowedAmount: int("maximum_allowed_amount").notNull(),
  minimumAllowedAmount: int("minimum_allowed_amount").notNull(),
  lockinPeriod: smallint("lockin_period").notNull(),
  category: varchar("category", { length: 50 }).notNull(),
  dailyReturn: float("daily_return", { precision: 2 }).notNull(),
  isPopular: boolean("is_popular")
    .$default(() => false)
    .notNull(),

  ...metadata("MPRO"),
});

// export const Relations__MiningProfile = relations(
//   Table__MiningProfile,
//   ({ many }) => ({
//     orders: many(Table__MiningOrder),
//   }),
// );

// -------------------------
// Table__MiningOrder
// -------------------------

export const Table__MiningOrder = mysqlTable("mining_order", {
  id: autogeneratedId(),
  orderedBy: foreignId("ordered_by")
    .notNull()
    .references(() => Table__User.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amountInvested: int("amount_invested").notNull(),
  amountReceived: int("amount_received").default(0),
  miningProfileUsed: foreignId("mining_profile_used")
    .notNull()
    .references(() => Table__MiningProfile.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  miningStatus: investmentStatusEnums().$defaultFn(() => "ACTIVE"),

  ...metadata("MORD"),
});

// export const Relations__MiningOrder = relations(Table__MiningOrder, ({ one }) => ({
//   user: one(Table__User, {
//     fields: [Table__MiningOrder.orderedBy],
//     references: [Table__User.id],
//   }),
//   miningProfile: one(Table__MiningProfile, {
//     fields: [Table__MiningOrder.miningProfileUsed],
//     references: [Table__MiningProfile.id],
//   }),
// }));

// -------------------------
// Table__TradingOrder
// -------------------------

export const Table__TradingOrder = mysqlTable("trading_order", {
  id: autogeneratedId(),
  orderedBy: foreignId("ordered_by")
    .notNull()
    .references(() => Table__User.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amountInvested: int("amount_invested").notNull(),
  amountReceived: int("amount_received").default(0),
  tradingStatus: investmentStatusEnums().$defaultFn(() => "ACTIVE"),

  ...metadata("TORD"),
});

// export const Relations__TradingOrder = relations(
//   Table__TradingOrder,
//   ({ one }) => ({
//     user: one(Table__User, {
//       fields: [Table__TradingOrder.orderedBy],
//       references: [Table__User.id],
//     }),
//   }),
// );

// -------------------------
// Table__MiningWalletDeposits
// -------------------------

export const Table__MiningWalletDeposits = mysqlTable(
  "mining_wallet_deposits",
  {
    id: autogeneratedId(),
    orderedBy: foreignId("ordered_by")
      .notNull()
      .references(() => Table__User.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    wallet: foreignId("wallet")
      .notNull()
      .references(() => Table__MiningWallet.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    amount: int("amount").notNull(),
    status: depositStatusEnums(),
    depositMethod: transactionMethodEnums("deposit_method").notNull(),
    transactionId: varchar("transaction_id", { length: 127 }).notNull(),
    depositProof: varchar("deposit_proof", { length: 255 }).notNull(),

    ...metadata("MWDP"),
  },
);

// export const Relations__MiningWalletDeposits = relations(
//   Table__MiningWalletDeposits,
//   ({ one }) => ({
//     user: one(Table__User, {
//       fields: [Table__MiningWalletDeposits.orderedBy],
//       references: [Table__User.id],
//     }),
//     wallet: one(Table__MiningWallet, {
//       fields: [Table__MiningWalletDeposits.wallet],
//       references: [Table__MiningWallet.id],
//     }),
//   }),
// );

// -------------------------
// Table__TradingWalletDeposits
// -------------------------

export const Table__TradingWalletDeposits = mysqlTable(
  "trading_wallet_deposits",
  {
    id: autogeneratedId(),
    orderedBy: foreignId("ordered_by")
      .notNull()
      .references(() => Table__User.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    wallet: foreignId("wallet")
      .notNull()
      .references(() => Table__TradingWallet.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    amount: int("amount").notNull(),
    status: depositStatusEnums(),
    depositMethod: transactionMethodEnums("deposit_method").notNull(),
    transactionId: varchar("transaction_id", { length: 127 }).notNull(),
    depositProof: varchar("deposit_proof", { length: 255 }).notNull(),

    ...metadata("TWDP"),
  },
);

// export const Relations__TradingWalletDeposits = relations(
//   Table__TradingWalletDeposits,
//   ({ one }) => ({
//     user: one(Table__User, {
//       fields: [Table__TradingWalletDeposits.orderedBy],
//       references: [Table__User.id],
//     }),
//     wallet: one(Table__TradingWallet, {
//       fields: [Table__TradingWalletDeposits.wallet],
//       references: [Table__TradingWallet.id],
//     }),
//   }),
// );

// -------------------------
// Table__MiningWalletWithdraw
// -------------------------

export const Table__MiningWalletWithdraw = mysqlTable(
  "mining_wallet_withdraw",
  {
    id: autogeneratedId(),
    orderedBy: foreignId("ordered_by")
      .notNull()
      .references(() => Table__User.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    wallet: foreignId("wallet")
      .notNull()
      .references(() => Table__MiningWallet.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    amount: int("amount").notNull(),
    cryptoWalletAddress: varchar("crypto_wallet_address", {
      length: 255,
    }).notNull(),
    status: withdrawlStatusEnums(),
    withdrawalMethod: transactionMethodEnums("withdrawal_method").notNull(),

    ...metadata("MWWD"),
  },
);

// export const Relations__MiningWalletWithdraw = relations(
//   Table__MiningWalletWithdraw,
//   ({ one }) => ({
//     user: one(Table__User, {
//       fields: [Table__MiningWalletWithdraw.orderedBy],
//       references: [Table__User.id],
//     }),
//     wallet: one(Table__MiningWallet, {
//       fields: [Table__MiningWalletWithdraw.wallet],
//       references: [Table__MiningWallet.id],
//     }),
//   }),
// );

// -------------------------
// Table__TradingWalletWithdraw
// -------------------------

export const Table__TradingWalletWithdraw = mysqlTable(
  "trading_wallet_withdraw",
  {
    id: autogeneratedId(),
    orderedBy: foreignId("ordered_by")
      .notNull()
      .references(() => Table__User.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    wallet: foreignId("wallet")
      .notNull()
      .references(() => Table__TradingWallet.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    amount: int("amount").notNull(),
    cryptoWaletAddress: varchar("crypto_walet_address", {
      length: 255,
    }).notNull(),
    status: withdrawlStatusEnums(),
    withdrawlMethod: transactionMethodEnums("withdrawl_method").notNull(),

    ...metadata("TWWD"),
  },
);

// export const Relations__TradingWalletWithdraw = relations(
//   Table__TradingWalletWithdraw,
//   ({ one }) => ({
//     user: one(Table__User, {
//       fields: [Table__TradingWalletWithdraw.orderedBy],
//       references: [Table__User.id],
//     }),
//     wallet: one(Table__TradingWallet, {
//       fields: [Table__TradingWalletWithdraw.wallet],
//       references: [Table__TradingWallet.id],
//     }),
//   }),
// );

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
export type TableIdentifierToken =
  /**
   * Table__User
   */
  | "USER"
  /**
   * Table__Rating
   */
  | "RTNG"
  /**
   * Table__MiningWallet
   */
  | "MWAL"
  /**
   * Table__News
   */
  | "NEWS"
  /**
   * Table__MiningOrder
   */
  | "MORD"
  /**
   * Table__TradingOrder
   */
  | "TORD"
  /**
   * Table__MiningProfile
   */
  | "MPRO"
  /**
   * Table__TradingWallet
   */
  | "TWAL"
  /**
   * Table__TradingWalletDeposits
   */
  | "TWDP"
  /**
   * TradingWalletWithdrawsTable
   */
  | "TWWD"
  /**
   * Table__MiningWalletDeposits
   */
  | "MWDP"
  /**
   * Table__MiningWalletWithdraw
   */
  | "MWWD";

export function roleEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "role", ROLE);
}

export function transactionMethodEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "transaction_method", TRANSACTION_METHOD);
}

export function userStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "user_status", USER_STATUS).$defaultFn(
    () => "ACTIVE",
  );
}

export function investmentStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "investment_status", INVESTMENT_STATUS);
}

export function depositStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "deposit_status", DEPOSIT_STATUS).$defaultFn(
    () => "PENDING",
  );
}

export function withdrawlStatusEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "withdrawl_status", WITHDRAWL_STATUS);
}
export function updatedAt(columnName?: string) {
  return timestamp(columnName ?? "updated_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
}
export function createdAt(columnName?: string) {
  return timestamp(columnName ?? "created_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
}
export function metadata(token: TableIdentifierToken) {
  return {
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    tableIdentifierToken: tokenColumn(token),
  };
}
export function tableIdentifierToken(columnName?: string) {
  return mysqlEnum(columnName ?? "table_identifier_token", [
    "USER",
    "TWAL",
    "MWAL",
    "RTNG",
    "MORD",
    "NEWS",
    "MPRO",
    "TORD",
    "TWDP",
    "TWWD",
    "MWDP",
    "MWWD",
  ] as [TableIdentifierToken, ...TableIdentifierToken[]]);
}
export function tokenColumn(token: TableIdentifierToken) {
  return tableIdentifierToken().notNull().default(token);
}
export function autogeneratedId() {
  return char("id", { length: 10 })
    .primaryKey()
    .$defaultFn(() => id());
}
export function foreignId(columnName: string) {
  return char(columnName, { length: 10 });
}

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */

const tableMap = {
  USER: "user",
  TWAL: "trading_wallet",
  MWAL: "mining_wallet",
  NEWS: "news",
  RTNG: "rating",
  TORD: "trading_order",
  MORD: "mining_order",
  MPRO: "mining_profile",
  TWDP: "trading_wallet_deposits",
  TWWD: "trading_wallet_withdraw",
  MWDP: "mining_wallet_deposits",
  MWWD: "mining_wallet_withdraw",
} as const;

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 *
 */

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
