import {
  mysqlTable,
  int,
  varchar,
  mysqlEnum,
  char,
  timestamp,
  float,
  tinyint,
  smallint,
  boolean,
  foreignKey,
} from "drizzle-orm/mysql-core";
import { id } from "@repo/utils/id";
import { relations } from "drizzle-orm";

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
export type TableIdentifierToken =
  /**
   * UserTable
   */
  | "USER"
  /**
   * RatingTable
   */
  | "RTNG"
  /**
   * MiningWalletTable
   */
  | "MWAL"
  /**
   * NewsTable
   */
  | "NEWS"
  /**
   * MiningOrderTable
   */
  | "MORD"
  /**
   * TradingOrderTable
   */
  | "TORD"
  /**
   * MiningProfileTable
   */
  | "MPRO"
  /**
   * TradingWalletTable
   */
  | "TWAL";

export const roleEnums = mysqlEnum("role", ["admin", "basic"]);
export const userStatusEnums = (columnName?: string) =>
  mysqlEnum(columnName ?? "user_status", ["active", "inactive", "blocked"]);
export const investmentStatusEnums = mysqlEnum("investment_status", [
  "active",
  "completed",
]);
export const updatedAt = () =>
  timestamp("updated_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
export const createdAt = () =>
  timestamp("created_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
export const metadataTimestamp = {
  createdAt: createdAt(),
  updatedAt: updatedAt(),
};
export const tableIdentifierToken = mysqlEnum("table_identifier_token", [
  "USER",
  "TWAL",
  "MWAL",
  "RTNG",
  "MORD",
  "NEWS",
  "MPRO",
  "TORD",
] as [TableIdentifierToken, ...TableIdentifierToken[]]);
export const tokenColumn = (token: TableIdentifierToken) =>
  tableIdentifierToken.notNull().default(token);
export const autogeneratedId = () =>
  char("id", { length: 10 })
    .primaryKey()
    .$defaultFn(() => id());

// -------------------------
// UserTable
// -------------------------

export const UserTable = mysqlTable(
  "users",
  {
    id: autogeneratedId(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    fullName: varchar("full_name", { length: 255 }).notNull(),
    avatarUrl: varchar("avatar_url", { length: 255 }).notNull(),
    age: int("age").notNull(),
    role: roleEnums.notNull().$default(() => "basic"),
    phoneNumber: char("phone_number", { length: 10 }).notNull(),
    referrerId: char("referrer_id", { length: 10 }),
    userStatus: userStatusEnums(),

    ...metadataTimestamp,
    tableIdentifierToken: tokenColumn("USER"),
  },

  (table) => [
    foreignKey({
      columns: [table.referrerId],
      foreignColumns: [table.id],
      name: "users_referrer_id_fk",
    })
      .onDelete("set null")
      .onUpdate("cascade"),
  ],
);

// -------------------------
// TradingWalletTable
// -------------------------

export const TradingWalletTable = mysqlTable("trading_wallet", {
  id: autogeneratedId(),
  balance: float("balance", { precision: 2 }).$default(() => 0),
  associatedUser: char("associated_user", { length: 10 })
    .unique()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("TWAL"),
});

// -------------------------
// MiningWalletTable
// -------------------------

export const MiningWalletTable = mysqlTable("mining_wallet", {
  id: autogeneratedId(),
  balance: float("balance", { precision: 2 }).$default(() => 0),
  associatedUser: char("associated_user", { length: 10 })
    .unique()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("MWAL"),
});

// -------------------------
// RatingTable
// -------------------------

export const RatingTable = mysqlTable("rating", {
  id: autogeneratedId(),
  associatedUser: char("associated_user", { length: 10 })
    .unique()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),
  ratingStar: tinyint("rating_star_count")
    .$defaultFn(() => 1)
    .notNull(),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("RTNG"),
});

// -------------------------
// NewsTable
// -------------------------

export const NewsTable = mysqlTable("news", {
  id: autogeneratedId(),
  effectiveDate: timestamp("effective_date", {
    mode: "date",
    fsp: 6,
  }).notNull(),
  heading: varchar("heading", { length: 255 }).notNull(),
  details: varchar("details", { length: 1023 }).notNull(),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("NEWS"),
});

// -------------------------
// MiningProfileTable
// -------------------------

export const MiningProfileTable = mysqlTable("mining_profile", {
  id: autogeneratedId(),
  maximumAllowedAmount: int("maximum_allowed_amount").notNull(),
  minimumAllowedAmount: int("minimum_allowed_amount").notNull(),
  lockinPeriod: smallint("lockin_period").notNull(),
  category: varchar("category", { length: 50 }).notNull(),
  dailyReturn: float("daily_return", { precision: 2 }).notNull(),
  isPopular: boolean("is_popular")
    .$default(() => false)
    .notNull(),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("MPRO"),
});

// -------------------------
// MiningOrderTable
// -------------------------

export const MiningOrderTable = mysqlTable("mining_order", {
  id: autogeneratedId(),
  orderedBy: char("ordered_by", { length: 10 })
    .notNull()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amountInvested: int("amount_invested").notNull(),
  amountRecived: int("amount_recived").default(0),
  miningProfileUsed: char("mining_profile_used", {
    length: 10,
  })
    .notNull()
    .references(() => MiningProfileTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  miningStatus: investmentStatusEnums.$defaultFn(() => "active"),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("MORD"),
});

// -------------------------
// TradingOrderTable
// -------------------------

export const TradingOrderTable = mysqlTable("trading_order", {
  id: autogeneratedId(),
  orderedBy: char("ordered_by", { length: 10 })
    .notNull()
    .references(() => UserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  amountInvested: int("amount_invested").notNull(),
  amountRecived: int("amount_recived").default(0),
  tradingStatus: investmentStatusEnums.$defaultFn(() => "active"),

  ...metadataTimestamp,
  tableIdentifierToken: tokenColumn("TORD"),
});

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------

export const UserRelations = relations(UserTable, ({ one, many }) => ({
  referredBy: one(UserTable, {
    fields: [UserTable.referrerId],
    references: [UserTable.id],
    relationName: "UserReferrals",
  }),

  referrals: many(UserTable, {
    relationName: "UserReferrals",
  }),

  tradingWallet: one(TradingWalletTable),
  miningWallet: one(MiningWalletTable),
  rating: one(RatingTable),
  miningOrders: many(MiningOrderTable),
  tradingOrders: many(TradingOrderTable),
}));

export const TradingWalletRelations = relations(
  TradingWalletTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [TradingWalletTable.associatedUser],
      references: [UserTable.id],
    }),
  }),
);

export const MiningWalletRelations = relations(
  MiningWalletTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [MiningWalletTable.associatedUser],
      references: [UserTable.id],
    }),
  }),
);

export const RatingRelations = relations(RatingTable, ({ one }) => ({
  user: one(UserTable, {
    fields: [RatingTable.associatedUser],
    references: [UserTable.id],
  }),
}));

export const MiningProfileRelations = relations(
  MiningProfileTable,
  ({ many }) => ({
    orders: many(MiningOrderTable),
  }),
);

export const MiningOrderRelations = relations(MiningOrderTable, ({ one }) => ({
  user: one(UserTable, {
    fields: [MiningOrderTable.orderedBy],
    references: [UserTable.id],
  }),
  miningProfile: one(MiningProfileTable, {
    fields: [MiningOrderTable.miningProfileUsed],
    references: [MiningProfileTable.id],
  }),
}));

export const TradingOrderRelations = relations(
  TradingOrderTable,
  ({ one }) => ({
    user: one(UserTable, {
      fields: [TradingOrderTable.orderedBy],
      references: [UserTable.id],
    }),
  }),
);

// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------
// ---------------------------------------------------------------

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */

const tableMap = {
  USER: "UserTable",
  TWAL: "TradingWalletTable",
  MWAL: "MiningWalletTable",
  NEWS: "NewsTable",
  RTNG: "RatingTable",
  TORD: "TradingOrderTable",
  MORD: "MiningOrderTable",
  MPRO: "MiningProfileTable",
} as const;

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 *
 */

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
