name: ai-minehub-dev

# the ports are derived from this, for consistent accross projects
# node -p "
# const c = require('crypto');
# const n = process.argv[1];
# const h = c.createHash('sha256').update(n).digest().readUInt32BE(0);
# 10000 + (h % 10000);
# " \
# container-name

networks:
  ai-minehub-dev:
    driver: bridge

services:
  ai-minehub-dev-database:
    container_name: ai-minehub-dev-database
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 14015:3306
    networks:
      - ai-minehub-dev
    volumes:
      - database:/var/lib/mysql

  ai-minehub-dev-phpmyadmin:
    container_name: ai-minehub-dev-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "17037:80"
    environment:
      PMA_HOST: ai-minehub-dev-database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - ai-minehub-dev-database
    networks:
      - ai-minehub-dev

  ai-minehub-dev-proxy:
    container_name: ai-minehub-dev-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ai-minehub-dev
    volumes:
      - ../nginx.secure.dev.conf:/etc/nginx/nginx.conf:ro
      - ../localhost-cert.pem:/etc/nginx/certs/localhost-cert.pem:ro
      - ../localhost-key.pem:/etc/nginx/certs/localhost-key.pem:ro

  # ai-minehub-dev-adguard:
  #   container_name: ai-minehub-dev-adguardhome
  #   image: adguard/adguardhome:edge
  #   restart: unless-stopped
  #   ports:
  #     - "15042:3000/tcp"
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #   networks:
  #     - ai-minehub-dev
  # volumes:
  #   - adguard-work:/opt/adguardhome/work
  #   - adguard-conf:/opt/adguardhome/conf

volumes:
  database:
  # adguard-work:
  # adguard-conf:
